// lib/copy/cbam-en.ts
export const CBAM_EN = {
  landing: {
    eyebrow: 'EU CBAM — for RGV manufacturers exporting to the EU',
    title: 'The EU now charges carbon at the border. We compose your CBAM report before the EU rejects your import.',
    sub: 'Definitive phase began January 1, 2026. Cement, iron/steel, aluminum, fertilizers, electricity, hydrogen — every shipment into the EU needs an Authorized CBAM Declarant + verified embedded-emissions data. RGV exporters: this is where you used to ship "no-questions-asked" steel and aluminum. That door closed Jan 1.',
    primary_cta: 'Run a free CBAM scan',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of CBAM cost saved (default vs verified) · $99 floor · no fee on rejected scans',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'CBAM is one wall. Cruzar protects the corridor.',
    border_layer_body: 'EU MDR for medtech. CBAM for steel + aluminum + fertilizers. EUDAMED, BREXIT EORI, EU AEO — every wall around the EU runs on a different filing. Cruzar Tickets are the unified record across them. The CBAM module composes onto the same chassis as EUDAMED, US customs, paperwork, and refunds. RGV exporters don\'t pick between CBAM compliance and operational speed — they get both via the same substrate.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free CBAM scan',
      step1_body: 'Tell us your declarant + one good. We classify the CN code, compute embedded emissions (default values or your verified data), and estimate certificate cost at current EU ETS price.',
      step2_title: '2. Sign up — quarterly CBAM report',
      step2_body: 'We compose the quarterly CBAM report XML for the EU CBAM Registry, surface every gap, and Ed25519-sign the package. Your authorized declarant submits it via the EU Registry.',
      step3_title: '3. Verifier engagement',
      step3_body: 'Default emission factors are conservative — verified actual data from the producing installation lowers your CBAM cost. We connect you to accredited CBAM verifiers in your installation\'s country.',
      step4_title: '4. Certificate purchase + reconcile',
      step4_body: 'You buy CBAM certificates from the EU Registry at weekly ETS auction price. We track surrenders + reconcile against your imports. Audit-shielded by the Cruzar Ticket chain.',
    },
    pricing: {
      eyebrow: 'Platform fee — paid only on cost saved',
      rate: '8% of CBAM cost reduction (verified vs default-value baseline)',
      floor: '$99 minimum on any CBAM filing processed',
      no_fee: 'No fee on scans that hit no in-scope goods (out-of-CBAM-scope)',
      no_retainer: 'No retainer. No subscription. The platform fee fires when verified-data savings land.',
    },
    sectors: {
      eyebrow: 'In-scope sectors',
      cement_title: 'Cement (CN 2523)',
      cement_body: 'Portland clinker + finished cement. Default direct: 0.766 t CO2e/t.',
      iron_steel_title: 'Iron & steel (CN 72-73)',
      iron_steel_body: 'Primary steel + downstream products. Default direct: 1.880 t CO2e/t.',
      aluminum_title: 'Aluminum (CN 76)',
      aluminum_body: 'Primary aluminum is electricity-intensive — indirect emissions dominate. Default total: 10.14 t CO2e/t.',
      fertilizers_title: 'Fertilizers (CN 28-31 selected)',
      fertilizers_body: 'Ammonia + urea + nitrates. Default direct: 1.620 t CO2e/t.',
      electricity_title: 'Electricity (CN 2716)',
      electricity_body: 'Grid imports. Default 0.475 t CO2e/MWh.',
      hydrogen_title: 'Hydrogen (CN 2804)',
      hydrogen_body: 'Grey, blue, green hydrogen treated separately. Default direct: 8.9 t CO2e/t.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free CBAM readiness check',
    sub: 'Enter your declarant and one good (CN code, mass, installation). We classify, compute embedded emissions, and estimate certificate cost. No signup, no payment, no commitment.',
    section_declarant: 'CBAM declarant',
    declarant_name_label: 'Declarant legal name',
    declarant_eori_label: 'EORI number',
    declarant_authorized_label: 'Authorized CBAM Declarant (definitive phase)',
    declarant_period_label: 'Reporting period (e.g. 2026-Q2)',
    section_good: 'Good',
    cn_code_label: 'CN code (8 digits)',
    description_label: 'Description',
    mass_label: 'Mass (tonnes)',
    section_installation: 'Producing installation',
    installation_name_label: 'Installation name',
    installation_country_label: 'Country (ISO-2)',
    installation_emp_label: 'Has Emissions Monitoring Plan',
    section_emissions: 'Embedded emissions',
    emissions_basis_label: 'Emissions basis',
    emissions_basis_actual_verified: 'Actual verified (lowest cost)',
    emissions_basis_actual_unverified: 'Actual unverified',
    emissions_basis_default: 'Default value (highest cost)',
    direct_emissions_label: 'Direct (Scope 1) emissions — t CO2e/t (optional)',
    indirect_emissions_label: 'Indirect (electricity) emissions — t CO2e/t (optional)',
    submit: 'Run the CBAM scan',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    summary_title: 'CBAM composition',
    summary_phase: 'Phase',
    summary_in_scope: 'Goods in scope',
    summary_total_mass: 'Total mass (tonnes)',
    summary_embedded_emissions: 'Total embedded emissions (t CO2e)',
    summary_certificates: 'Certificates required',
    summary_estimated_cost: 'Estimated CBAM cost (EUR)',
    summary_ets_price: 'ETS reference price (EUR/t)',
    summary_findings: 'Findings',
    summary_no_fatal: 'No fatal findings — composition ready for the EU CBAM Registry',
    cta_after: 'Sign up to compose the full quarterly CBAM XML',
    cta_subnote: 'Quarterly XML + verifier engagement + certificate reconcile included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for preparing EU CBAM documentation. Cruzar does not file with the EU CBAM Registry on your behalf, does not provide accredited verification, and is not an Authorized CBAM Declarant. Filings prepared via Cruzar must be reviewed and submitted by an Authorized CBAM Declarant; emissions data must be verified by an accredited CBAM verifier when claiming actual values.',
  },
};
