// lib/copy/cbam-es.ts
export const CBAM_ES = {
  landing: {
    eyebrow: 'CBAM UE — para fabricantes RGV que exportan a la UE',
    title: 'La UE ya cobra carbono en frontera. Componemos tu reporte CBAM antes de que la UE te rechace la importación.',
    sub: 'La fase definitiva inició el 1 de enero de 2026. Cemento, hierro/acero, aluminio, fertilizantes, electricidad, hidrógeno — cada envío a la UE necesita un Declarante CBAM Autorizado + datos verificados de emisiones incrustadas. Exportadores RGV: aquí es donde antes mandaban acero y aluminio "sin preguntas". Esa puerta se cerró el 1 de enero.',
    primary_cta: 'Corre un escaneo gratis',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa plataforma: 8% del costo CBAM ahorrado (default vs verificado) · piso $99 · sin tarifa en escaneos rechazados',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'CBAM es un muro. Cruzar protege el corredor.',
    border_layer_body: 'EU MDR para medtech. CBAM para acero + aluminio + fertilizantes. EUDAMED, EORI BREXIT, AEO UE — cada muro alrededor de la UE corre sobre un trámite distinto. Los Cruzar Tickets son el registro unificado a través de ellos. El módulo CBAM compone sobre el mismo chasis que EUDAMED, customs US, papelería y reembolsos. Los exportadores RGV no escogen entre cumplimiento CBAM y velocidad operativa — obtienen ambos vía el mismo substrato.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis',
      step1_body: 'Dinos tu declarante + una mercancía. Clasificamos el código CN, calculamos emisiones incrustadas (valores default o tus datos verificados), y estimamos costo de certificados al precio actual del EU ETS.',
      step2_title: '2. Regístrate — reporte trimestral CBAM',
      step2_body: 'Componemos el XML del reporte trimestral CBAM para el Registro CBAM UE, marcamos cada brecha, y firmamos Ed25519. Tu declarante autorizado lo envía por el Registro UE.',
      step3_title: '3. Verificador acreditado',
      step3_body: 'Los factores de emisión por defecto son conservadores — datos verificados reales de la instalación productora bajan tu costo CBAM. Te conectamos con verificadores CBAM acreditados en el país de la instalación.',
      step4_title: '4. Compra de certificados + reconciliación',
      step4_body: 'Compras certificados CBAM en el Registro UE al precio semanal de subasta ETS. Rastreamos entregas + reconciliamos contra tus importaciones. Escudo de auditoría por la cadena Cruzar Ticket.',
    },
    pricing: {
      eyebrow: 'Tarifa plataforma — pagada solo sobre costo ahorrado',
      rate: '8% de la reducción de costo CBAM (verificado vs línea base default)',
      floor: '$99 mínimo sobre cualquier presentación CBAM procesada',
      no_fee: 'Sin tarifa en escaneos sin mercancías en alcance (fuera-de-CBAM)',
      no_retainer: 'Sin retainer. Sin suscripción. La tarifa se dispara cuando aterriza el ahorro por dato verificado.',
    },
    sectors: {
      eyebrow: 'Sectores en alcance',
      cement_title: 'Cemento (CN 2523)',
      cement_body: 'Clínker portland + cemento terminado. Default directo: 0.766 t CO2e/t.',
      iron_steel_title: 'Hierro y acero (CN 72-73)',
      iron_steel_body: 'Acero primario + productos descendentes. Default directo: 1.880 t CO2e/t.',
      aluminum_title: 'Aluminio (CN 76)',
      aluminum_body: 'El aluminio primario es electrointensivo — emisiones indirectas dominan. Default total: 10.14 t CO2e/t.',
      fertilizers_title: 'Fertilizantes (CN 28-31 selectos)',
      fertilizers_body: 'Amoníaco + urea + nitratos. Default directo: 1.620 t CO2e/t.',
      electricity_title: 'Electricidad (CN 2716)',
      electricity_body: 'Importaciones de red. Default 0.475 t CO2e/MWh.',
      hydrogen_title: 'Hidrógeno (CN 2804)',
      hydrogen_body: 'Hidrógeno gris, azul, verde tratados por separado. Default directo: 8.9 t CO2e/t.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Verificación gratis de preparación CBAM',
    sub: 'Ingresa tu declarante y una mercancía (código CN, masa, instalación). Clasificamos, calculamos emisiones incrustadas, y estimamos costo de certificados. Sin registro, sin pago, sin compromiso.',
    section_declarant: 'Declarante CBAM',
    declarant_name_label: 'Nombre legal del declarante',
    declarant_eori_label: 'Número EORI',
    declarant_authorized_label: 'Declarante CBAM Autorizado (fase definitiva)',
    declarant_period_label: 'Periodo de reporte (e.g. 2026-Q2)',
    section_good: 'Mercancía',
    cn_code_label: 'Código CN (8 dígitos)',
    description_label: 'Descripción',
    mass_label: 'Masa (toneladas)',
    section_installation: 'Instalación productora',
    installation_name_label: 'Nombre de la instalación',
    installation_country_label: 'País (ISO-2)',
    installation_emp_label: 'Tiene Plan de Monitoreo de Emisiones',
    section_emissions: 'Emisiones incrustadas',
    emissions_basis_label: 'Base de emisiones',
    emissions_basis_actual_verified: 'Real verificada (costo más bajo)',
    emissions_basis_actual_unverified: 'Real sin verificar',
    emissions_basis_default: 'Valor default (costo más alto)',
    direct_emissions_label: 'Emisiones directas (Alcance 1) — t CO2e/t (opcional)',
    indirect_emissions_label: 'Emisiones indirectas (electricidad) — t CO2e/t (opcional)',
    submit: 'Corre el escaneo CBAM',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa — intenta en una hora.',
    summary_title: 'Composición CBAM',
    summary_phase: 'Fase',
    summary_in_scope: 'Mercancías en alcance',
    summary_total_mass: 'Masa total (toneladas)',
    summary_embedded_emissions: 'Total emisiones incrustadas (t CO2e)',
    summary_certificates: 'Certificados requeridos',
    summary_estimated_cost: 'Costo CBAM estimado (EUR)',
    summary_ets_price: 'Precio referencia ETS (EUR/t)',
    summary_findings: 'Hallazgos',
    summary_no_fatal: 'Sin hallazgos fatales — composición lista para el Registro CBAM UE',
    cta_after: 'Regístrate para componer el XML trimestral CBAM completo',
    cta_subnote: 'XML trimestral + verificador + reconciliación de certificados incluidos.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para preparar documentación CBAM UE. Cruzar no presenta ante el Registro CBAM UE en tu nombre, no provee verificación acreditada, y no es un Declarante CBAM Autorizado. Las presentaciones preparadas vía Cruzar deben ser revisadas y enviadas por un Declarante CBAM Autorizado; los datos de emisiones deben ser verificados por un verificador CBAM acreditado al reclamar valores reales.',
  },
};
