// lib/copy/drawback-es.ts
export const DRAWBACK_ES = {
  landing: {
    eyebrow: 'Drawback aduanal US — para importadores + exportadores',
    title: 'Pagaste aranceles sobre mercancía que exportaste, re-exportaste o devolviste. CBP te debe el 99% de regreso.',
    sub: 'El §1313 del Código Aduanal US recupera 99% de aranceles, impuestos y cargos sobre importaciones que se exportan, se usan para fabricar exportaciones, o se rechazan por defecto. Ventana de 5 años. La mayoría de importadores nunca lo reclama.',
    primary_cta: 'Corre un escaneo gratis',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa plataforma: 8% del reembolso procesado · piso $99 · sin tarifa en reclamos rechazados o vencidos',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'Drawback es un muro. Cruzar protege el corredor.',
    border_layer_body: 'Drawback (§1313) y reembolsos IEEPA corren sobre el mismo chasis que validación aduanal, extracción de papelería, notificación pre-arribo y cumplimiento de operadores. Un Cruzar Ticket lleva cada módulo que se disparó en un envío — firmado Ed25519, listo para auditoría. Drawback no es una herramienta aislada; es el espejo del lado-exportación de la recuperación de reembolsos que ya confías.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis',
      step1_body: 'Dinos una importación + una exportación. Clasificamos el tipo de reclamo según §1313, validamos la ventana de 5 años, y te decimos cuánto puedes recuperar. Sin registro.',
      step2_title: '2. Regístrate — componemos Form 7551',
      step2_body: 'Componemos el reclamo CBP Form 7551 con designaciones §1313 correctas: manufactura ID directa, manufactura sustitución, mercancía sin usar ID directa, mercancía sin usar sustitución, o mercancía rechazada. Firmado Ed25519.',
      step3_title: '3. Fianza + pago acelerado',
      step3_body: 'Obtén el privilegio de pago acelerado (~3 semanas vs ~12 meses) colocando una fianza de drawback. Te guiamos en la solicitud del privilegio CBP + colocación de fianza.',
      step4_title: '4. Presenta + rastrea',
      step4_body: 'Tu agente aduanal licenciado presenta el reclamo vía ACE. Nosotros rastreamos el reloj. Cobramos sobre dinero confirmado — nunca sobre esperanza.',
    },
    pricing: {
      eyebrow: 'Tarifa plataforma — pagada solo cuando el reembolso llega',
      rate: '8% del drawback procesado por la plataforma Cruzar',
      floor: '$99 mínimo sobre cualquier reclamo procesado',
      no_fee: 'Sin tarifa sobre presentaciones rechazadas, vencidas, o retiradas',
      no_retainer: 'Sin retainer. Sin suscripción. La tarifa se dispara solo cuando CBP paga el drawback a tu ACH.',
    },
    claim_types: {
      eyebrow: 'Qué puedes reclamar',
      manufacturing_direct_title: 'Manufactura — ID directa (§1313(a))',
      manufacturing_direct_body: 'Mercancía importada usada en manufactura de artículo exportado. Mismo HTSUS de 10 dígitos o método contable aprobado.',
      manufacturing_sub_title: 'Manufactura — sustitución (§1313(b))',
      manufacturing_sub_body: 'Mercancía importada y sustituida comercialmente intercambiable usada en producción para exportación. Test de 8 dígitos HTSUS post-TFTEA.',
      unused_direct_title: 'Sin usar — ID directa (§1313(j)(1))',
      unused_direct_body: 'Mercancía importada re-exportada en la misma condición. Mismo HTSUS de 10 dígitos.',
      unused_sub_title: 'Sin usar — sustitución (§1313(j)(2))',
      unused_sub_body: 'Mercancía sin usar sustituida comercialmente intercambiable. Test de 8 dígitos HTSUS.',
      rejected_title: 'Mercancía rechazada (§1313(c))',
      rejected_body: 'Importaciones defectuosas, no conformes, o enviadas sin consentimiento devueltas dentro de 5 años del import.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Verificación gratis de elegibilidad §1313',
    sub: 'Ingresa una importación + una exportación. Clasificamos el tipo de reclamo, verificamos la ventana de 5 años, y estimamos tu recuperación. Sin registro, sin pago, sin compromiso.',
    section_claimant: 'Reclamante',
    claimant_name_label: 'Nombre legal del reclamante',
    claimant_id_label: 'EIN / número IRS',
    section_entry: 'Importación',
    entry_number_label: 'Número entry ACE (14 dígitos)',
    entry_date_label: 'Fecha entry (AAAA-MM-DD)',
    htsus_label: 'Código HTSUS (10 dígitos)',
    duty_paid_label: 'Arancel pagado (USD)',
    fees_paid_label: 'MPF + HMF pagado (USD)',
    units_label: 'Cantidad de unidades',
    section_export: 'Exportación',
    export_id_label: 'Referencia export (BOL o AES)',
    export_date_label: 'Fecha export (AAAA-MM-DD)',
    export_htsus_label: 'HTSUS export o Schedule B',
    export_units_label: 'Unidades exportadas',
    destination_label: 'País destino (ISO-2)',
    section_evidence: 'Evidencia',
    mfg_evidence_label: 'Evidencia de manufactura',
    mfg_evidence_none: 'Ninguna — re-exportada en misma condición',
    mfg_evidence_bom: 'Lista de materiales (BOM)',
    mfg_evidence_record: 'Registro de manufactura',
    rejection_evidence_label: 'Evidencia de rechazo',
    rejection_evidence_none: 'No es mercancía rechazada',
    rejection_evidence_inspection: 'Reporte de inspección / QC',
    rejection_evidence_return: 'Aviso de devolución del cliente',
    submit: 'Corre el escaneo de drawback',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa — intenta en una hora.',
    summary_title: 'Estimación de recuperación drawback',
    summary_claim_type: 'Tipo de reclamo',
    summary_eligible: 'Elegible',
    summary_ineligible: 'No elegible',
    summary_refund_basis: 'Base reembolsable (arancel + impuesto + cargo)',
    summary_drawback: 'Drawback recuperable (99%)',
    summary_estimated_fee: 'Tarifa plataforma Cruzar (8%)',
    summary_net_to_you: 'Neto estimado para ti',
    cta_after: 'Regístrate para componer Form 7551',
    cta_subnote: 'Form 7551 + guía de fianza + onboarding ACH incluidos.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para preparar documentación de drawback CBP. Cruzar no realiza transacciones aduanales con CBP y no es un agente aduanal licenciado. Las presentaciones preparadas vía Cruzar deben ser revisadas y presentadas por el agente aduanal licenciado responsable. Los reembolsos de drawback los paga CBP directamente al ACH del importador; Cruzar nunca custodia dinero de reembolso.',
  },
};
