// lib/copy/drawback-en.ts
export const DRAWBACK_EN = {
  landing: {
    eyebrow: 'US duty drawback — for U.S. importers + exporters',
    title: 'You paid duties on goods you exported, re-exported, or returned. CBP owes you 99% of it back.',
    sub: 'US Customs §1313 drawback recovers 99% of duties, taxes, and fees on imports that get exported, used to manufacture exports, or rejected as defective. 5-year filing window. Most importers never claim it.',
    primary_cta: 'Run a free drawback scan',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of refund processed · $99 floor · no fee on rejected or expired claims',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'Drawback is one wall. Cruzar protects the corridor.',
    border_layer_body: 'Drawback (§1313) and IEEPA refunds run on the same chassis as customs validation, paperwork extraction, regulatory pre-arrival, and driver compliance. One Cruzar Ticket carries every module that fired on a shipment — Ed25519-signed, audit-ready. Drawback isn\'t a standalone tool; it\'s the export-side mirror of the import-side refund recovery you already trust.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free drawback scan',
      step1_body: 'Tell us one import + one export. We classify the claim type per §1313, check the 5-year window, and tell you how much you can recover. No signup.',
      step2_title: '2. Sign up — compose Form 7551',
      step2_body: 'We compose the CBP Form 7551 drawback claim with proper §1313 designations: manufacturing direct ID, manufacturing substitution, unused merch direct ID, unused merch substitution, or rejected merchandise. Ed25519-signed.',
      step3_title: '3. Bond + accelerated payment',
      step3_body: 'Get accelerated payment privilege (~3 weeks vs ~12 months) by posting a drawback bond. We walk you through CBP\'s privilege application + bond placement.',
      step4_title: '4. File + track',
      step4_body: 'Your licensed broker files the claim through ACE. We track the refund clock. We charge our fee on confirmed money — never on hope.',
    },
    pricing: {
      eyebrow: 'Platform fee — paid only on drawback that comes back',
      rate: '8% of drawback processed through Cruzar\'s filing platform',
      floor: '$99 minimum on any processed claim',
      no_fee: 'No fee on rejected, expired, or withdrawn filings',
      no_retainer: 'No retainer. No subscription. The platform fee fires only when CBP pays the drawback into your ACH.',
    },
    claim_types: {
      eyebrow: 'What you can claim',
      manufacturing_direct_title: 'Manufacturing — direct ID (§1313(a))',
      manufacturing_direct_body: 'Imported merchandise used in manufacturing an exported article. Same 10-digit HTSUS or approved accounting method.',
      manufacturing_sub_title: 'Manufacturing — substitution (§1313(b))',
      manufacturing_sub_body: 'Imported and substituted commercially-interchangeable merch used in producing exports. 8-digit HTSUS test post-TFTEA.',
      unused_direct_title: 'Unused merch — direct ID (§1313(j)(1))',
      unused_direct_body: 'Imported merchandise re-exported in the same condition. Same 10-digit HTSUS.',
      unused_sub_title: 'Unused merch — substitution (§1313(j)(2))',
      unused_sub_body: 'Substituted unused commercially-interchangeable merchandise. 8-digit HTSUS test.',
      rejected_title: 'Rejected merchandise (§1313(c))',
      rejected_body: 'Defective, non-conforming, or shipped-without-consent imports returned within 5 years of import.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free §1313 drawback eligibility check',
    sub: 'Enter one import + one export. We\'ll classify the claim type, check the 5-year window, and estimate your recovery. No signup, no payment, no commitment.',
    section_claimant: 'Claimant',
    claimant_name_label: 'Claimant legal name',
    claimant_id_label: 'EIN / IRS number',
    section_entry: 'Import entry',
    entry_number_label: 'ACE entry number (14 digits)',
    entry_date_label: 'Entry date (YYYY-MM-DD)',
    htsus_label: 'HTSUS code (10 digits)',
    duty_paid_label: 'Duty paid (USD)',
    fees_paid_label: 'MPF + HMF paid (USD)',
    units_label: 'Unit count',
    section_export: 'Export',
    export_id_label: 'Export reference (BOL or AES)',
    export_date_label: 'Export date (YYYY-MM-DD)',
    export_htsus_label: 'Export HTSUS or Schedule B',
    export_units_label: 'Units exported',
    destination_label: 'Destination country (ISO-2)',
    section_evidence: 'Evidence',
    mfg_evidence_label: 'Manufacturing evidence',
    mfg_evidence_none: 'None — re-exported in same condition',
    mfg_evidence_bom: 'Bill of materials',
    mfg_evidence_record: 'Manufacturing record',
    rejection_evidence_label: 'Rejection evidence',
    rejection_evidence_none: 'Not rejected merchandise',
    rejection_evidence_inspection: 'Inspection / QC report',
    rejection_evidence_return: 'Customer return notice',
    submit: 'Run the drawback scan',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    summary_title: 'Drawback recovery estimate',
    summary_claim_type: 'Claim type',
    summary_eligible: 'Eligible',
    summary_ineligible: 'Not eligible',
    summary_refund_basis: 'Refund basis (duty + tax + fee)',
    summary_drawback: 'Drawback recoverable (99%)',
    summary_estimated_fee: 'Cruzar platform fee (8%)',
    summary_net_to_you: 'Estimated net to you',
    cta_after: 'Sign up to compose Form 7551',
    cta_subnote: 'Form 7551 + bond walkthrough + ACH onboarding included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for preparing CBP drawback documentation. Cruzar does not transact CBP business and is not a licensed customs broker. Filings prepared via Cruzar must be reviewed and submitted by the licensed customs broker of record. Drawback refunds are paid by CBP directly to the importer\'s ACH; Cruzar never custodies refund money.',
  },
};
