// lib/copy/driver-pass-es.ts
export const DRIVER_PASS_ES = {
  landing: {
    eyebrow: 'Driver Pass — para flotas y operadores independientes',
    title: 'No dejes que una TWIC vencida mate una carga de $4,000. Compón el pase del operador antes de que ruede el camión.',
    sub: 'CDL, tarjeta médica DOT, TWIC, FAST/SENTRI, FMM, endoso HAZMAT — cada viaje necesita una pila distinta de documentos vigentes. Cruzar revisa la pila contra el viaje, marca lo vencido o lo que vence en menos de 30 días, y emite un pase firmado que viaja con la carga.',
    primary_cta: 'Corre un escaneo gratis',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa plataforma: 8% de los $ de detención evitados · piso $99 · sin tarifa en escaneos rechazados',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'Driver pass es un muro. Cruzar protege el corredor.',
    border_layer_body: 'El complemento del lado del operador a "cumplimiento de operadores" (HOS, IMSS, Anexo 31-A). El mismo Cruzar Ticket que lleva customs + pedimento + regulatorio + reembolsos ahora lleva un bloque driver-pass — todo el envío + el operador detrás del volante firman al mismo substrato. Oficial CBP, inspector aduanal MX, agente, dispatcher, operador — mismo registro.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis',
      step1_body: 'Dinos el operador, el viaje (origen + destino + hazmat + perecederos), y una pila de documentos con fechas de vencimiento. Clasificamos cada uno, marcamos lo vencido, exponemos lo que vence pronto, y evaluamos la preparación general.',
      step2_title: '2. Regístrate — emite los pases',
      step2_body: 'Cuando está verde, emitimos un pase Apple Wallet + link escaneable QR + referencia Cruzar Ticket. El operador lo carga en su teléfono; el agente carga el payload firmado.',
      step3_title: '3. Rastreo de vencimientos',
      step3_body: 'Los operadores reciben recordatorios email + SMS 60, 30 y 7 días antes de que venza cualquier documento requerido. Dispatch ve un dashboard de preparación a nivel flota — sin bloqueos sorpresa.',
      step4_title: '4. Archivo listo para auditoría',
      step4_body: 'Cada pase + hallazgo se firma en el Cruzar Ticket. Si un operador es retenido en inspección secundaria, el registro contemporáneo prueba el estado de preparación al momento de composición.',
    },
    pricing: {
      eyebrow: 'Tarifa plataforma — pagada solo sobre $ de detención evitados',
      rate: '8% de los dólares de detención evitados (referencia $85/hr × horas ahorradas)',
      floor: '$99 mínimo sobre cualquier pase emitido',
      no_fee: 'Sin tarifa en escaneos sin documentos por vencer (operador ya estaba listo)',
      no_retainer: 'Sin retainer. Sin suscripción. La tarifa se dispara cuando una bandera de doc-vencido provoca una renovación que evita detención.',
    },
    docs: {
      eyebrow: 'Documentos que rastreamos',
      cdl_title: 'CDL (Licencia Comercial) — 49 CFR Parte 383',
      cdl_body: 'Emitida por el estado. 4 años típico. El endoso hazmat requiere evaluación TSA.',
      medical_title: 'Tarjeta médica DOT — 49 CFR § 391.41',
      medical_body: '24 meses típico. Sin ella, FMCSA te pone fuera-de-servicio en la primera inspección.',
      twic_title: 'TWIC — 49 CFR § 1572',
      twic_body: 'Requerida para acceso a puertos. 5 años. Tiempo de renovación: 6-8 semanas.',
      fast_title: 'FAST / SENTRI — Viajero Confiable CBP',
      fast_body: 'Cruce comercial / peatonal más rápido. 5 años, condicional al comportamiento del operador + C-TPAT del transportista.',
      fmm_title: 'Permiso FMM — INM México',
      fmm_body: 'Forma Migratoria Múltiple. Requerida para operadores no mexicanos entrando a MX. Validez 180 días.',
      hazmat_title: 'Endoso HAZMAT',
      hazmat_body: 'Endoso CDL para transporte de materiales peligrosos. Evaluación TSA + examen estatal.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Verificación gratis de preparación del operador',
    sub: 'Ingresa el operador, el viaje, y una pila de documentos. Evaluamos preparación general, marcamos lo vencido o lo que vence en 30 días, y emitimos un payload de pase por viaje. Sin registro, sin pago, sin compromiso.',
    section_driver: 'Operador',
    driver_name_label: 'Nombre legal del operador',
    cdl_number_label: 'Número CDL',
    cdl_state_label: 'Estado del CDL (2 letras)',
    section_trip: 'Viaje',
    origin_label: 'Origen',
    destination_label: 'Destino',
    crossing_port_label: 'Código del puerto/aduana',
    eta_label: 'ETA programada',
    hazmat_label: 'Carga hazmat',
    perishables_label: 'Carga perecedera',
    section_docs: 'Documentos',
    add_doc: 'Agregar documento',
    remove_doc: 'Eliminar',
    doc_id_label: 'ID del doc (cdl, twic, medical, fmm, hazmat_endorsement, ...)',
    doc_label_label: 'Etiqueta visible',
    doc_expiry_label: 'Fecha de vencimiento',
    submit: 'Corre el escaneo de preparación',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa — intenta en una hora.',
    summary_title: 'Composición de pase',
    summary_readiness: 'Preparación',
    summary_blocking: 'Documentos bloqueantes',
    summary_expiring: 'Vencen en 30 días',
    summary_findings: 'Hallazgos por documento',
    summary_actions: 'Acciones recomendadas',
    summary_ready: 'Operador listo — payload de pase emitido',
    cta_after: 'Regístrate para emitir pases Apple Wallet + recordatorios',
    cta_subnote: 'Pase Apple Wallet + QR + recordatorios email + SMS incluidos.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para rastrear vencimientos de documentos del operador y componer payloads de pase por viaje. Cruzar no emite credenciales gubernamentales (CDL, TWIC, FMM, etc.); las emiten sus agencias respectivas. El payload de pase es solo para fines operativos y de auditoría.',
  },
};
