// lib/copy/driver-pass-en.ts
export const DRIVER_PASS_EN = {
  landing: {
    eyebrow: 'Driver Pass — for fleet operators + owner-operators',
    title: 'Don\'t let an expired TWIC kill a $4,000 load. Compose a per-trip driver pass before the truck rolls.',
    sub: 'CDL, DOT medical, TWIC, FAST/SENTRI, FMM, HAZMAT endorsement — every trip needs a different stack of documents in date. Cruzar checks the stack against the trip, flags expired or expiring-within-30-days, and emits a signed driver pass that travels with the load.',
    primary_cta: 'Run a free driver readiness scan',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of detention $ avoided · $99 floor · no fee on rejected scans',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'Driver pass is one wall. Cruzar protects the corridor.',
    border_layer_body: 'The driver-side complement to operator-level driver compliance (HOS, IMSS, Annex 31-A). The same Cruzar Ticket that carries customs + pedimento + regulatory + refunds blocks now carries a driver-pass block — the whole shipment + the driver behind the wheel sign onto one substrate. CBP officer, Mexican aduana inspector, broker, dispatcher, driver — same record.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free readiness scan',
      step1_body: 'Tell us the driver, the trip (origin + destination + hazmat + perishables), and a stack of documents with expiry dates. We classify each, flag expired, surface expiring-soon, and assess overall readiness.',
      step2_title: '2. Sign up — issue passes',
      step2_body: 'When green, we issue an Apple Wallet pass + QR-scannable link + Cruzar Ticket reference. The driver carries it on phone; the broker carries the signed payload.',
      step3_title: '3. Expiry tracking',
      step3_body: 'Drivers get email + SMS reminders 60, 30, and 7 days before any required document expires. Dispatch sees a fleet-level readiness dashboard — no surprise blockages.',
      step4_title: '4. Audit-ready archive',
      step4_body: 'Every pass + finding signs into the Cruzar Ticket. If a driver is held at secondary inspection, the contemporaneous record proves the readiness state at composition time.',
    },
    pricing: {
      eyebrow: 'Platform fee — paid only on detention $ avoided',
      rate: '8% of detention dollars avoided (per the standard $85/hr × hours-saved benchmark)',
      floor: '$99 minimum on any pass issued',
      no_fee: 'No fee on scans that find no expiring docs (driver was already ready)',
      no_retainer: 'No retainer. No subscription. The platform fee fires when an expiring-doc flag triggers a renewal that prevents detention.',
    },
    docs: {
      eyebrow: 'Documents we track',
      cdl_title: 'CDL (Commercial Driver\'s License) — 49 CFR Part 383',
      cdl_body: 'State-issued. 4-year typical. Hazmat endorsement requires TSA threat assessment.',
      medical_title: 'DOT medical card — 49 CFR § 391.41',
      medical_body: '24-month typical. Without it, the FMCSA puts you out-of-service at the first inspection.',
      twic_title: 'TWIC — 49 CFR § 1572',
      twic_body: 'Required for port access. 5-year. Renewal lead time: 6-8 weeks.',
      fast_title: 'FAST / SENTRI — CBP Trusted Traveler',
      fast_body: 'Faster commercial / pedestrian crossing. 5-year, conditional on driver behavior + carrier C-TPAT.',
      fmm_title: 'FMM permit — INM Mexico',
      fmm_body: 'Forma Migratoria Múltiple. Required for non-Mexican drivers entering MX. 180-day validity.',
      hazmat_title: 'HAZMAT endorsement',
      hazmat_body: 'CDL endorsement for hazardous materials transport. TSA threat assessment + state knowledge test.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free driver readiness check',
    sub: 'Enter the driver, the trip, and a stack of documents. We assess overall readiness, flag expired or expiring-within-30-days, and issue a per-trip pass payload. No signup, no payment, no commitment.',
    section_driver: 'Driver',
    driver_name_label: 'Driver legal name',
    cdl_number_label: 'CDL number',
    cdl_state_label: 'CDL state (2-letter)',
    section_trip: 'Trip',
    origin_label: 'Origin',
    destination_label: 'Destination',
    crossing_port_label: 'Crossing port code',
    eta_label: 'Scheduled ETA',
    hazmat_label: 'Hazmat load',
    perishables_label: 'Perishables load',
    section_docs: 'Documents',
    add_doc: 'Add document',
    remove_doc: 'Remove',
    doc_id_label: 'Doc id (cdl, twic, medical, fmm, hazmat_endorsement, ...)',
    doc_label_label: 'Display label',
    doc_expiry_label: 'Expiry date',
    submit: 'Run the readiness scan',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    summary_title: 'Driver pass composition',
    summary_readiness: 'Readiness',
    summary_blocking: 'Blocking documents',
    summary_expiring: 'Expiring within 30 days',
    summary_findings: 'Document findings',
    summary_actions: 'Recommended actions',
    summary_ready: 'Driver ready — pass payload issued',
    cta_after: 'Sign up to issue Apple Wallet passes + reminders',
    cta_subnote: 'Apple Wallet pass + QR + email + SMS reminders included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for tracking driver-document expiry and composing per-trip pass payloads. Cruzar does not issue government-recognized credentials (CDL, TWIC, FMM, etc.); those are issued by their respective agencies. The pass payload is for operational and audit purposes only.',
  },
};
