// lib/copy/eudamed-en.ts
export const EUDAMED_EN = {
  landing: {
    eyebrow: 'EU MDR / EUDAMED — for Reynosa medtech',
    title: 'EUDAMED is mandatory May 28, 2026.',
    sub: 'Every medtech manufacturer, importer, and authorized representative selling into the EU has to be on the actor + UDI/Device modules of EUDAMED. Most Reynosa maquilas and their OEM customers don\'t have the data structured. Cruzar captures it during your cross-border events.',
    deadline_label: 'Days until EUDAMED mandatory',
    primary_cta: 'Run a free actor + UDI readiness check',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of compliance-attached refund or invoice processed · $99 floor · no fee on rejected or expired filings',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'Reynosa runs the implants. Cruzar carries the data feed.',
    border_layer_body: 'The EU has EUDAMED. The US has FDA UDI / GUDID. Mexico\'s maquila layer has neither — yet ships into both markets. Cruzar Ticket already captures HS classification, country of origin, supplier breakdown, and regulatory submissions on every cross-border event. Add UDI-DI/PI capture during the Ticket pass and you have an EUDAMED-ready record by default. We prepare; your OEM\'s compliance team submits.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free actor + UDI readiness check',
      step1_body: 'Tell us your actor role (manufacturer, AR, importer, distributor) and one device. We tell you what EUDAMED requires + what\'s missing. No signup.',
      step2_title: '2. Sign up — capture devices during cross-border events',
      step2_body: 'Each Cruzar Ticket can carry an EUDAMED block: UDI-DI, UDI-PI, GMDN, risk class, NB ID, CE marking.',
      step3_title: '3. Export the EUDAMED feed',
      step3_body: 'JSON for actor registration. CSV for UDI/Device module. Your OEM compliance team uploads to EUDAMED — Cruzar never submits on your behalf.',
      step4_title: '4. Audit-ready archive',
      step4_body: 'Every Ticket Ed25519-signed and time-stamped. If a competent authority audits the actor or device data, the chain of custody is provable.',
    },
    pricing: {
      eyebrow: 'Pricing — paid only on compliance-attached commerce',
      rate: '8% platform fee on compliance-attached refund or invoice processed through Cruzar',
      floor: '$99 minimum on any processed event',
      no_fee: 'No fee on rejected or expired filings — same way payment processors don\'t bill declined transactions',
      no_retainer: 'No retainer. No subscription. No hidden EU-consultant markup.',
    },
  },
  scan: {
    eyebrow: 'Free EUDAMED readiness check',
    title: 'Free EUDAMED readiness check',
    sub: 'Tell us your actor + one device. We tell you what EUDAMED requires and what\'s missing. No signup, no payment, no commitment.',
    actor_section: 'Actor (the legal entity that places the device on the EU market)',
    device_section: 'Device (one example for the readiness check)',
    actor_legal_name: 'Legal name',
    actor_role_label: 'Actor role',
    actor_country: 'Registration country (ISO-2)',
    actor_email: 'Compliance contact email',
    actor_srn: 'EUDAMED SRN (leave blank if not yet registered)',
    actor_ar_srn: 'Authorized representative SRN (required if non-EU manufacturer)',
    device_brand: 'Brand name (as on labelling)',
    device_model: 'Model / catalogue number',
    device_di: 'UDI-DI (GS1 GTIN — 14 digits)',
    device_gmdn_code: 'GMDN code',
    device_gmdn_term: 'GMDN term',
    device_class_label: 'Risk class',
    device_nb: 'EU Notified Body ID (4-digit)',
    device_ce_label: 'CE marking',
    submit: 'Run readiness check',
    checking: 'Checking...',
    summary_title: 'Readiness summary',
    actor_ready: 'Actor registration is ready to submit',
    actor_blocked: 'Actor registration NOT ready — fields missing',
    device_ready: 'Device record is EUDAMED-valid',
    device_blocked: 'Device record NOT valid — fields missing',
    cta_after: 'Sign up to capture full inventory through Ticket',
    cta_subnote: 'Onboarding + actor + UDI registry + audit log included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for preparing EU MDR/IVDR EUDAMED documentation. Cruzar does not submit data to EUDAMED, does not act as an EU authorized representative, and is not a legal manufacturer. The legal manufacturer or authorized representative under EU MDR/IVDR is responsible for all EUDAMED submissions. We capture the data; your team submits.',
  },
};
