// lib/copy/eudamed-es.ts
export const EUDAMED_ES = {
  landing: {
    eyebrow: 'EU MDR / EUDAMED — para medtech de Reynosa',
    title: 'EUDAMED es obligatorio el 28 de mayo de 2026.',
    sub: 'Cada fabricante, importador, o representante autorizado de dispositivos médicos que vende a la UE tiene que estar en los módulos de actor + UDI/Dispositivo de EUDAMED. La mayoría de las maquilas de Reynosa y sus clientes OEM no tienen la data estructurada. Cruzar la captura durante tus eventos transfronterizos.',
    deadline_label: 'Días hasta EUDAMED obligatorio',
    primary_cta: 'Verificación gratis de preparación actor + UDI',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa de plataforma: 8% del reembolso o factura de cumplimiento procesado · piso $99 · sin cargo en presentaciones rechazadas o vencidas',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'Reynosa fabrica los implantes. Cruzar lleva la data.',
    border_layer_body: 'La UE tiene EUDAMED. EE.UU. tiene FDA UDI / GUDID. La capa maquilera mexicana no tiene ninguna — y vende a ambos mercados. Cruzar Ticket ya captura clasificación HS, país de origen, desglose de proveedores, y presentaciones regulatorias en cada evento transfronterizo. Agrega captura UDI-DI/PI durante el Ticket y tienes un registro EUDAMED listo por default. Nosotros preparamos; el equipo de cumplimiento de tu OEM presenta.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Verificación gratis de preparación actor + UDI',
      step1_body: 'Dinos tu rol de actor (fabricante, RA, importador, distribuidor) y un dispositivo. Te decimos qué requiere EUDAMED + qué falta. Sin registro.',
      step2_title: '2. Regístrate — captura dispositivos durante eventos transfronterizos',
      step2_body: 'Cada Cruzar Ticket puede llevar un bloque EUDAMED: UDI-DI, UDI-PI, GMDN, clase de riesgo, ID de RA, marcado CE.',
      step3_title: '3. Exporta el feed EUDAMED',
      step3_body: 'JSON para registro de actor. CSV para módulo UDI/Dispositivo. El equipo de cumplimiento de tu OEM lo sube a EUDAMED — Cruzar nunca presenta en tu nombre.',
      step4_title: '4. Archivo listo para auditoría',
      step4_body: 'Cada Ticket firmado Ed25519 y con marca de tiempo. Si una autoridad competente audita la data del actor o del dispositivo, la cadena de custodia es comprobable.',
    },
    pricing: {
      eyebrow: 'Precio — solo se paga en comercio con cumplimiento adjunto',
      rate: '8% tarifa de plataforma sobre reembolso o factura de cumplimiento procesado a través de Cruzar',
      floor: '$99 mínimo en cualquier evento procesado',
      no_fee: 'Sin cargo en presentaciones rechazadas o vencidas — igual que los procesadores de pago no cobran transacciones declinadas',
      no_retainer: 'Sin anticipo. Sin suscripción. Sin sobreprecio oculto de consultor UE.',
    },
  },
  scan: {
    eyebrow: 'Verificación gratis EUDAMED',
    title: 'Verificación gratis de preparación EUDAMED',
    sub: 'Dinos tu actor + un dispositivo. Te decimos qué requiere EUDAMED y qué falta. Sin registro, sin pago, sin compromiso.',
    actor_section: 'Actor (la entidad legal que coloca el dispositivo en el mercado UE)',
    device_section: 'Dispositivo (un ejemplo para la verificación)',
    actor_legal_name: 'Razón social',
    actor_role_label: 'Rol del actor',
    actor_country: 'País de registro (ISO-2)',
    actor_email: 'Correo de contacto de cumplimiento',
    actor_srn: 'EUDAMED SRN (déjalo vacío si aún no estás registrado)',
    actor_ar_srn: 'SRN del representante autorizado (requerido si fabricante no-UE)',
    device_brand: 'Marca (como en etiqueta)',
    device_model: 'Modelo / número de catálogo',
    device_di: 'UDI-DI (GTIN GS1 — 14 dígitos)',
    device_gmdn_code: 'Código GMDN',
    device_gmdn_term: 'Término GMDN',
    device_class_label: 'Clase de riesgo',
    device_nb: 'ID Notified Body UE (4 dígitos)',
    device_ce_label: 'Marcado CE',
    submit: 'Correr verificación',
    checking: 'Verificando...',
    summary_title: 'Resumen de preparación',
    actor_ready: 'Registro de actor listo para presentar',
    actor_blocked: 'Registro de actor NO listo — faltan campos',
    device_ready: 'Registro de dispositivo válido para EUDAMED',
    device_blocked: 'Registro de dispositivo NO válido — faltan campos',
    cta_after: 'Regístrate para capturar inventario completo vía Ticket',
    cta_subnote: 'Onboarding + registro de actor + UDI + log de auditoría incluido.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para preparar documentación EU MDR/IVDR EUDAMED. Cruzar no presenta datos a EUDAMED, no actúa como representante autorizado UE, y no es fabricante legal. El fabricante legal o representante autorizado bajo EU MDR/IVDR es responsable de todas las presentaciones EUDAMED. Nosotros capturamos la data; tu equipo presenta.',
  },
};
