// lib/copy/pedimento-en.ts
export const PEDIMENTO_EN = {
  landing: {
    eyebrow: 'VUCEM / Pedimento — for Mexican customs brokers and importers',
    title: 'Compose pedimentos that pass the first VUCEM validation. Every time.',
    sub: 'Cruzar reads your operation, picks the right Anexo 22 clave (A1, V5, A3, M3...), validates RFC + patente + fracción + padrón status, and computes ad-valorem + DTA + IVA + IEPS — before VUCEM rejects the filing for you.',
    primary_cta: 'Run a free pedimento scan',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of recoverable / processed value · $99 floor · no fee on rejected scans',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'VUCEM is one wall. Cruzar protects the corridor.',
    border_layer_body: 'The US-MX corridor has ACE on one side, VUCEM on the other, fragmented brokers in between, and no shared compliance record. Cruzar Tickets are the unified record. The pedimento module composes onto the same chassis as US customs, paperwork, drivers, regulatory pre-arrival, IEEPA refunds, and drawback. Mexican brokers stop chasing rejections. US importers stop guessing what their MX counterparts are filing. One signed substrate.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free pedimento scan',
      step1_body: 'Tell us the operation (import / export / transit), the agent, the importer, and one merchandise line. We classify the clave per Anexo 22, validate the RFC + patente, and run the duty math.',
      step2_title: '2. Sign up — full pedimento + DODA',
      step2_body: 'We compose the full 33-field pedimento, the DODA carriage, and the documentary-package PDF. Ed25519-signed and persisted to your Cruzar Ticket.',
      step3_title: '3. Cross-check with US side',
      step3_body: 'When the same shipment has a Cruzar Ticket on the US side (CBP 7501, ISF, USMCA), the pedimento module cross-validates against it. Inconsistencies flag before VUCEM rejection.',
      step4_title: '4. File via your VUCEM credential',
      step4_body: 'Cruzar prepares the documents. Your patente files them through VUCEM via your existing credential. Cruzar never logs into VUCEM on your behalf.',
    },
    pricing: {
      eyebrow: 'Platform fee — paid only on confirmed value',
      rate: '8% of recoverable / processed pedimento value',
      floor: '$99 minimum on any processed pedimento',
      no_fee: 'No fee on scans that get rejected at composition or VUCEM validation',
      no_retainer: 'No retainer. No subscription. The platform fee fires when the pedimento clears VUCEM.',
    },
    claves: {
      eyebrow: 'Common claves we compose',
      a1_title: 'A1 — Importación definitiva',
      a1_body: 'Definitive import. Most common clave. Triggers full ad-valorem + DTA + IVA + IEPS.',
      v5_title: 'V5 — Importación temporal IMMEX',
      v5_body: 'Temporary import under IMMEX program. Reduced or zero duties. Returns require V6.',
      a3_title: 'A3 — Exportación definitiva',
      a3_body: 'Definitive export. No duties; tax-zero IVA; required for US drawback designations.',
      m3_title: 'M3 — Tránsito internacional',
      m3_body: 'In-transit cargo crossing Mexican territory. Bond required.',
      f4_title: 'F4 — Conversión virtual IMMEX',
      f4_body: 'Convert IMMEX temporary import to virtual export. The maquila workflow.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free pedimento composition check',
    sub: 'Enter the agent, the importer/exporter, and one merchandise line. We pick the clave, validate identifiers, and compute duties. No signup, no payment, no commitment.',
    section_agente: 'Customs broker',
    patente_label: 'Patente aduanal (4 digits)',
    agente_name_label: 'Broker name / firm',
    agente_rfc_label: 'Broker RFC',
    section_importador: 'Importer / Exporter',
    importador_rfc_label: 'RFC',
    importador_razon_label: 'Razón social',
    importador_estado_label: 'Domicilio fiscal — state (3-letter)',
    importador_padron_label: 'Padrón de Importadores active',
    importador_immex_label: 'IMMEX program number (optional)',
    section_operacion: 'Operation',
    operacion_label: 'Operation type',
    operacion_import: 'Import',
    operacion_export: 'Export',
    operacion_transit: 'In-transit',
    operacion_return: 'Return',
    regimen_label: 'Regimen',
    regimen_definitivo: 'Definitive',
    regimen_temporal: 'Temporary',
    regimen_deposito: 'Bonded warehouse',
    regimen_transito: 'In-transit',
    aduana_label: 'Aduana code (3 digits)',
    fecha_label: 'Operation date',
    section_mercancia: 'Merchandise (1 line)',
    fraccion_label: 'Fracción arancelaria (8 digits)',
    nico_label: 'NICO suffix (2 digits)',
    descripcion_label: 'Description',
    pais_origen_label: 'Country of origin (ISO-2)',
    pais_vendedor_label: 'Seller country (ISO-2)',
    cantidad_label: 'Quantity',
    unidad_label: 'Unit (PZA, KG, LTS...)',
    valor_factura_label: 'Invoice value (USD)',
    ad_valorem_label: 'Ad-valorem rate (%)',
    ieps_label: 'IEPS applicable',
    submit: 'Run the pedimento scan',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    summary_title: 'Pedimento composition',
    summary_clave: 'Clave (Anexo 22)',
    summary_regimen: 'Regimen',
    summary_rfc_validation: 'RFC validation',
    summary_patente_validation: 'Patente validation',
    summary_padron: 'Padrón status',
    summary_findings: 'Findings',
    summary_no_fatal: 'No fatal findings — pedimento ready for full composition',
    summary_total_value: 'Total invoice value',
    summary_ad_valorem: 'Ad-valorem',
    summary_dta: 'DTA (0.8%)',
    summary_iva: 'IVA',
    summary_ieps: 'IEPS',
    summary_total_contributions: 'Total contributions',
    cta_after: 'Sign up to compose the full pedimento + DODA',
    cta_subnote: 'Full 33-field pedimento + DODA + Cruzar Ticket included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for preparing Mexican customs documentation (pedimento, DODA, supporting docs). Cruzar does not file with VUCEM on your behalf, does not transact aduanal business, and is not a licensed customs broker (agente aduanal). Filings prepared via Cruzar must be reviewed and submitted by the licensed agente aduanal of record using their own VUCEM credential.',
  },
};
