// lib/copy/pedimento-es.ts
export const PEDIMENTO_ES = {
  landing: {
    eyebrow: 'VUCEM / Pedimento — para agentes aduanales e importadores mexicanos',
    title: 'Compón pedimentos que pasan la primera validación VUCEM. Siempre.',
    sub: 'Cruzar lee tu operación, escoge la clave correcta de Anexo 22 (A1, V5, A3, M3...), valida RFC + patente + fracción + estado del padrón, y calcula ad-valorem + DTA + IVA + IEPS — antes de que VUCEM te rechace el pedimento.',
    primary_cta: 'Corre un escaneo gratis',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa plataforma: 8% del valor recuperable / procesado · piso $99 · sin tarifa en escaneos rechazados',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'VUCEM es un muro. Cruzar protege el corredor.',
    border_layer_body: 'El corredor US-MX tiene ACE de un lado, VUCEM del otro, agentes fragmentados en medio, y ningún registro compartido de cumplimiento. El Cruzar Ticket es el registro unificado. El módulo de pedimento compone sobre el mismo chasis que customs US, papelería, operadores, regulatorio pre-arribo, reembolsos IEEPA y drawback. Los agentes aduanales dejan de cazar rechazos. Los importadores US dejan de adivinar qué presenta su contraparte MX. Un substrato firmado.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis',
      step1_body: 'Dinos la operación (importación / exportación / tránsito), el agente, el importador, y una mercancía. Clasificamos la clave por Anexo 22, validamos RFC + patente, y corremos las matemáticas.',
      step2_title: '2. Regístrate — pedimento completo + DODA',
      step2_body: 'Componemos el pedimento completo de 33 campos, la carta DODA, y el paquete documental PDF. Firmado Ed25519 y persistido en tu Cruzar Ticket.',
      step3_title: '3. Cruza-validación con el lado US',
      step3_body: 'Cuando el mismo envío tiene Cruzar Ticket del lado US (CBP 7501, ISF, USMCA), el módulo de pedimento valida cruzado contra él. Las inconsistencias se marcan antes del rechazo VUCEM.',
      step4_title: '4. Presenta con tu credencial VUCEM',
      step4_body: 'Cruzar prepara los documentos. Tu patente los presenta vía VUCEM con tu credencial existente. Cruzar nunca entra a VUCEM en tu nombre.',
    },
    pricing: {
      eyebrow: 'Tarifa plataforma — pagada solo sobre valor confirmado',
      rate: '8% del valor recuperable / procesado del pedimento',
      floor: '$99 mínimo sobre cualquier pedimento procesado',
      no_fee: 'Sin tarifa sobre escaneos rechazados en composición o validación VUCEM',
      no_retainer: 'Sin retainer. Sin suscripción. La tarifa se dispara cuando el pedimento limpia VUCEM.',
    },
    claves: {
      eyebrow: 'Claves comunes que componemos',
      a1_title: 'A1 — Importación definitiva',
      a1_body: 'Importación definitiva. La clave más común. Dispara ad-valorem + DTA + IVA + IEPS completos.',
      v5_title: 'V5 — Importación temporal IMMEX',
      v5_body: 'Importación temporal bajo programa IMMEX. Aranceles reducidos o cero. Retornos requieren V6.',
      a3_title: 'A3 — Exportación definitiva',
      a3_body: 'Exportación definitiva. Sin aranceles; IVA tasa cero; requerida para designaciones drawback US.',
      m3_title: 'M3 — Tránsito internacional',
      m3_body: 'Carga en tránsito cruzando territorio mexicano. Fianza requerida.',
      f4_title: 'F4 — Conversión virtual IMMEX',
      f4_body: 'Convierte importación temporal IMMEX a exportación virtual. El flujo de la maquila.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Verificación gratis de composición pedimento',
    sub: 'Ingresa el agente, el importador/exportador, y una mercancía. Escogemos la clave, validamos identificadores, y calculamos contribuciones. Sin registro, sin pago, sin compromiso.',
    section_agente: 'Agente aduanal',
    patente_label: 'Patente aduanal (4 dígitos)',
    agente_name_label: 'Nombre / razón social del agente',
    agente_rfc_label: 'RFC del agente',
    section_importador: 'Importador / Exportador',
    importador_rfc_label: 'RFC',
    importador_razon_label: 'Razón social',
    importador_estado_label: 'Domicilio fiscal — estado (3 letras)',
    importador_padron_label: 'Padrón de Importadores activo',
    importador_immex_label: 'Número de programa IMMEX (opcional)',
    section_operacion: 'Operación',
    operacion_label: 'Tipo de operación',
    operacion_import: 'Importación',
    operacion_export: 'Exportación',
    operacion_transit: 'Tránsito',
    operacion_return: 'Retorno',
    regimen_label: 'Régimen',
    regimen_definitivo: 'Definitivo',
    regimen_temporal: 'Temporal',
    regimen_deposito: 'Depósito fiscal',
    regimen_transito: 'Tránsito',
    aduana_label: 'Código aduana (3 dígitos)',
    fecha_label: 'Fecha de operación',
    section_mercancia: 'Mercancía (1 línea)',
    fraccion_label: 'Fracción arancelaria (8 dígitos)',
    nico_label: 'Sufijo NICO (2 dígitos)',
    descripcion_label: 'Descripción',
    pais_origen_label: 'País de origen (ISO-2)',
    pais_vendedor_label: 'País del vendedor (ISO-2)',
    cantidad_label: 'Cantidad',
    unidad_label: 'Unidad (PZA, KG, LTS...)',
    valor_factura_label: 'Valor factura (USD)',
    ad_valorem_label: 'Tasa ad-valorem (%)',
    ieps_label: 'IEPS aplicable',
    submit: 'Corre el escaneo de pedimento',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa — intenta en una hora.',
    summary_title: 'Composición de pedimento',
    summary_clave: 'Clave (Anexo 22)',
    summary_regimen: 'Régimen',
    summary_rfc_validation: 'Validación RFC',
    summary_patente_validation: 'Validación patente',
    summary_padron: 'Estado padrón',
    summary_findings: 'Hallazgos',
    summary_no_fatal: 'Sin hallazgos fatales — pedimento listo para composición completa',
    summary_total_value: 'Valor total factura',
    summary_ad_valorem: 'Ad-valorem',
    summary_dta: 'DTA (0.8%)',
    summary_iva: 'IVA',
    summary_ieps: 'IEPS',
    summary_total_contributions: 'Total contribuciones',
    cta_after: 'Regístrate para componer el pedimento completo + DODA',
    cta_subnote: 'Pedimento completo de 33 campos + DODA + Cruzar Ticket incluidos.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para preparar documentación aduanal mexicana (pedimento, DODA, soportes). Cruzar no presenta ante VUCEM en tu nombre, no realiza transacciones aduanales, y no es un agente aduanal licenciado. Las presentaciones preparadas vía Cruzar deben ser revisadas y presentadas por el agente aduanal licenciado responsable usando su propia credencial VUCEM.',
  },
};
