// lib/copy/refunds-en.ts
export const REFUNDS_EN = {
  landing: {
    eyebrow: 'IEEPA refunds — for U.S. importers',
    title: 'You paid IEEPA tariffs. The Supreme Court struck them down. We help you get the money back.',
    sub: '$166 billion is owed across 330,000 importers. 83% haven\'t even set up the bank account to receive it. We start you there — for free.',
    primary_cta: 'Run a free eligibility scan',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of refund processed · $99 floor · no fee on rejected or expired filings',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'The EU has EORI. The US-MX border has Cruzar.',
    border_layer_body: 'In Europe, every importer has a single EORI number, every trusted operator earns AEO status, customs records are unified across 27 countries. Across the US-MX border, you have ACE on one side, VUCEM on the other, fragmented brokers in between, and no shared compliance record. Cruzar Tickets are the unified record. Refunds are one of five modules running on it — customs, regulatory, paperwork, drivers, refunds. Built on the border, for the border.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free eligibility scan',
      step1_body: 'Drop your ACE Entry Summary CSV. We tell you what you\'re owed in under a minute. No signup required.',
      step2_title: '2. Sign up — get the filing',
      step2_body: 'We compose the CAPE CSV using revenue codes REV-615 (CAPE credit) + REV-613 (ACH rejection tracking) — the codes CBP\'s system reads since CAPE went live April 20, 2026. For entries whose individual 80-day protest window has closed, we draft a Form 19 protest packet instead. Both documents are Ed25519-signed.',
      step3_title: '3. ACE / ACH onboarding',
      step3_body: 'You can\'t receive a refund without an ACE Portal account + ACH enrollment. We walk you through both — most filers haven\'t set this up.',
      step4_title: '4. Submit + track',
      step4_body: 'You file with CBP. We track the 60-day refund clock. When it hits your account, mark it received — we charge our fee on confirmed money, never on hope.',
    },
    pricing: {
      eyebrow: 'Platform fee — paid only on refunds that come back',
      rate: '8% of refund processed through Cruzar\'s filing platform',
      floor: '$99 minimum on any processed refund',
      no_fee: 'No fee on rejected, expired, or withdrawn filings — same way payment processors don\'t bill declined transactions',
      no_retainer: 'No retainer. No subscription. The platform fee fires only when CBP pays the refund into your ACH.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free eligibility scan',
    sub: 'Drop your ACE Entry Summary CSV. We tell you what you\'re owed in under a minute. No signup, no payment, no commitment.',
    drop_label: 'Drop CSV here, or click to upload',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    parse_failed: 'CSV parse failed. Make sure it\'s an ACE Entry Summary export.',
    summary_title: 'Recovery summary',
    summary_total_recoverable: 'Total recoverable',
    summary_principal: 'IEEPA principal',
    summary_interest: 'Interest accrued',
    summary_cape_eligible: 'CAPE-eligible (Phase 1 fast lane)',
    summary_protest_required: 'Form 19 protest required',
    summary_past_window: 'Past 180-day window',
    summary_estimated_fee: 'Cruzar platform fee (8% on processed refund)',
    summary_net_to_you: 'Estimated net to you',
    cta_after: 'Sign up to compose the filing',
    cta_subnote: 'CAPE CSV + Form 19 packet + ACE/ACH onboarding included.',
  },
  setup: {
    eyebrow: 'ACE / ACH onboarding',
    title: 'Set up to receive your refund',
    sub: '83% of importers haven\'t set this up. CBP can\'t pay you without an ACE Portal account + ACH enrollment. 4 steps. We track your progress.',
    step1_title: '1. ACE Portal account',
    step1_body: 'Apply at CBP\'s Trade Portal. Takes 24-48 hours to activate.',
    step1_link_label: 'CBP Trade Portal getting-started →',
    step1_link_url: 'https://www.cbp.gov/trade/automated/getting-started',
    step2_title: '2. ACH Refund Authorization',
    step2_body: 'In the ACE Portal, find "ACH Refund Authorization." Enter the bank routing + account number for the refund. We only need the last 4 digits of each — for our records.',
    step3_title: '3. CBP Form 4811 (optional)',
    step3_body: 'Form 4811 lets a broker or agent receive notices on your behalf. Optional — skip if your broker isn\'t involved.',
    step4_title: '4. Compile your IEEPA-paid entry list',
    step4_body: 'In ACE Reports, run an Entry Summary export covering the IEEPA period (Feb 1, 2025 onward). Save as CSV. That\'s the file you upload to Cruzar.',
    step4_link_label: 'How to run an ACE Entry Summary report →',
    step4_link_url: 'https://www.cbp.gov/trade/ace',
    status_not_started: 'Not started',
    status_pending: 'Pending',
    status_active: 'Active',
    status_enrolled: 'Enrolled',
    save: 'Save progress',
    saving: 'Saving...',
    saved: 'Saved.',
    bank_routing_label: 'Bank routing — last 4 digits',
    bank_account_label: 'Bank account — last 4 digits',
  },
  claims: {
    eyebrow: 'My claims',
    title: 'Refund claims',
    new_claim: 'Start a new claim',
    empty_title: 'No claims yet',
    empty_body: 'Run a free scan to see what you\'re owed, then start a claim.',
    empty_cta: 'Run a free scan',
    col_id: 'Claim',
    col_ior: 'IOR',
    col_entries: 'Entries',
    col_recoverable: 'Recoverable',
    col_status: 'Status',
    col_updated: 'Updated',
    status_draft: 'Draft',
    status_validated: 'Validated',
    status_submitted_to_ace: 'Submitted',
    status_refund_in_transit: 'In transit',
    status_refund_received: 'Received',
    status_rejected: 'Rejected',
    new_form_title: 'New refund claim',
    ior_name_label: 'Importer of Record (legal name)',
    ior_id_label: 'IOR number (EIN or CBP-assigned)',
    filer_code_label: 'Filer code (3-letter, optional)',
    language_label: 'Filing language',
    create: 'Create draft',
    creating: 'Creating...',
  },
  detail: {
    back: '← Back to claims',
    section_summary: 'Summary',
    section_entries: 'Entries',
    section_actions: 'Actions',
    label_ior: 'Importer of Record',
    label_filer_code: 'Filer code',
    label_total_entries: 'Total entries',
    label_principal_owed: 'Principal owed',
    label_interest_owed: 'Interest accrued',
    label_recoverable: 'Total recoverable',
    label_cape_eligible: 'CAPE-eligible',
    label_protest_required: 'Form 19 protest required',
    label_past_window: 'Past 180-day window',
    label_status: 'Status',
    label_cape_claim_number: 'CAPE claim number',
    label_received_amount: 'Received amount',
    label_cruzar_fee: 'Cruzar fee',
    upload_label: 'Upload ACE Entry Summary CSV',
    uploading: 'Uploading + composing...',
    upload_help: 'Drop your ACE Entry Summary CSV. We compose CAPE + Form 19 and persist the entries to this claim.',
    download_cape: 'Download CAPE CSV',
    download_form19: 'Download Form 19 packet',
    mark_submitted: 'I submitted to ACE',
    mark_submitted_modal_title: 'Confirm submission',
    mark_submitted_field: 'CAPE claim number (if CBP returned one)',
    mark_received: 'I received the refund',
    mark_received_modal_title: 'Mark refund received',
    mark_received_field: 'Actual amount received (USD)',
    confirm: 'Confirm',
    cancel: 'Cancel',
    entry_col_number: 'Entry #',
    entry_col_country: 'Origin',
    entry_col_eo: 'EO',
    entry_col_principal: 'IEEPA paid',
    entry_col_interest: 'Interest',
    entry_col_cliff: 'Cliff',
    section_broker_of_record: 'Broker of record',
    broker_of_record_help: 'A licensed customs broker must review the prepared filing and submit it to CBP. Cruzar prepares; the broker files. Required before submission.',
    broker_name_label: 'Broker name (firm or individual)',
    broker_license_label: 'CBP broker license #',
    broker_attest_label: 'I confirm this licensed broker has reviewed the prepared CAPE CSV and (if present) Form 19 packet, and will be the broker of record on this filing.',
    section_ior_attestation: 'Importer of Record attestation',
    ior_attest_help: 'The Importer of Record must attest they reviewed the filing and authorize submission. False statements on a CBP refund claim may carry penalties under 31 USC § 3729.',
    ior_attest_signer_label: 'Signer name (Importer of Record authorized representative)',
    ior_attest_label: 'I am authorized to act for the Importer of Record. I have reviewed the prepared filing and authorize the broker of record to submit it to CBP on the IOR\'s behalf.',
    save_attestation: 'Save attestation',
    saved: 'Saved',
    submission_blocked_broker: 'Submission blocked — designate and attest a licensed broker of record first.',
    submission_blocked_ior: 'Submission blocked — IOR must attest the filing first.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for preparing CBP refund documentation. Cruzar does not transact CBP business and is not a licensed customs broker. Filings prepared via Cruzar must be reviewed and submitted by the licensed customs broker of record. Refunds are paid by CBP directly to the importer\'s ACH; Cruzar never custodies refund money.',
  },
};
