// lib/copy/refunds-es.ts
export const REFUNDS_ES = {
  landing: {
    eyebrow: 'Reembolsos IEEPA — para importadores EE.UU.',
    title: 'Pagaste aranceles IEEPA. La Corte Suprema los anuló. Te ayudamos a recuperar tu dinero.',
    sub: '$166 mil millones se deben a 330,000 importadores. 83% ni siquiera configuraron la cuenta bancaria para recibirlos. Empezamos ahí — gratis.',
    primary_cta: 'Escaneo gratis de elegibilidad',
    secondary_cta: 'Cómo funciona',
    pricing_strip: '5% sobre primeros $50K · 3% en $50K–$500K · 1.5% superior · piso $99 · gratis si no hay recuperación',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'La UE tiene EORI. La frontera EE.UU.–México tiene Cruzar.',
    border_layer_body: 'En Europa, cada importador tiene un solo número EORI, cada operador de confianza gana estatus AEO, los registros aduanales están unificados en 27 países. En la frontera EE.UU.–México tienes ACE de un lado, VUCEM del otro, brokers fragmentados en medio, y cero registro compartido. Los Tickets Cruzar son ese registro unificado. Los reembolsos son uno de cinco módulos que corren sobre él — aduanas, regulatorio, papeleo, conductores, reembolsos. Construido en la frontera, para la frontera.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis de elegibilidad',
      step1_body: 'Sube tu CSV de ACE Entry Summary. Te decimos cuánto te deben en menos de un minuto. Sin registro.',
      step2_title: '2. Regístrate — obtén la presentación',
      step2_body: 'Componemos el CSV CAPE (la plantilla rápida Phase 1 de CBP) más un paquete de protesta Form 19 para entradas pasadas del precipicio de 80 días. Ambos bilingües EN/ES. Ambos firmados Ed25519.',
      step3_title: '3. Onboarding ACE / ACH',
      step3_body: 'No puedes recibir un reembolso sin cuenta del Portal ACE + inscripción ACH. Te guiamos por los dos — la mayoría de los filers no tienen esto configurado.',
      step4_title: '4. Envía + rastrea',
      step4_body: 'Tú presentas con CBP. Nosotros rastreamos el reloj de 60 días. Cuando llegue a tu cuenta, márcalo recibido — cobramos sobre dinero confirmado, nunca sobre esperanza.',
    },
    pricing: {
      eyebrow: 'Precio — solo cuando recuperas',
      tier1: '5% sobre los primeros $50K recuperados',
      tier2: '3% en $50K–$500K',
      tier3: '1.5% sobre $500K',
      floor: '$99 mínimo en cualquier reclamo exitoso',
      free: 'Gratis si no hay recuperación — cada paso. Sin anticipo.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Escaneo gratis de elegibilidad',
    sub: 'Sube tu CSV de ACE Entry Summary. Te decimos cuánto te deben en menos de un minuto. Sin registro, sin pago, sin compromiso.',
    drop_label: 'Suelta el CSV aquí, o haz clic para subir',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa excedido — intenta en una hora.',
    parse_failed: 'Falló el parseo del CSV. Asegúrate de que sea un export de ACE Entry Summary.',
    summary_title: 'Resumen de recuperación',
    summary_total_recoverable: 'Total recuperable',
    summary_principal: 'Principal IEEPA',
    summary_interest: 'Interés acumulado',
    summary_cape_eligible: 'Elegible CAPE (Phase 1 rápido)',
    summary_protest_required: 'Requiere protesta Form 19',
    summary_past_window: 'Pasada ventana de 180 días',
    summary_estimated_fee: 'Tarifa Cruzar (solo si recuperas)',
    summary_net_to_you: 'Neto estimado para ti',
    cta_after: 'Regístrate para componer la presentación',
    cta_subnote: 'CSV CAPE + paquete Form 19 + onboarding ACE/ACH incluidos.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
  },
};
