// lib/copy/refunds-en.ts
export const REFUNDS_EN = {
  landing: {
    eyebrow: 'IEEPA refunds — for U.S. importers',
    title: 'You paid IEEPA tariffs. The Supreme Court struck them down. We help you get the money back.',
    sub: '$166 billion is owed across 330,000 importers. 83% haven\'t even set up the bank account to receive it. We start you there — for free.',
    primary_cta: 'Run a free eligibility scan',
    secondary_cta: 'How it works',
    pricing_strip: '5% on first $50K · 3% on $50K–$500K · 1.5% above · $99 floor · free if no recovery',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'The EU has EORI. The US-MX border has Cruzar.',
    border_layer_body: 'In Europe, every importer has a single EORI number, every trusted operator earns AEO status, customs records are unified across 27 countries. Across the US-MX border, you have ACE on one side, VUCEM on the other, fragmented brokers in between, and no shared compliance record. Cruzar Tickets are the unified record. Refunds are one of five modules running on it — customs, regulatory, paperwork, drivers, refunds. Built on the border, for the border.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free eligibility scan',
      step1_body: 'Drop your ACE Entry Summary CSV. We tell you what you\'re owed in under a minute. No signup required.',
      step2_title: '2. Sign up — get the filing',
      step2_body: 'We compose the CAPE CSV (CBP\'s Phase 1 fast-lane refund template) plus a Form 19 protest packet for entries past the 80-day cliff. Both bilingual EN/ES. Both Ed25519-signed.',
      step3_title: '3. ACE / ACH onboarding',
      step3_body: 'You can\'t receive a refund without an ACE Portal account + ACH enrollment. We walk you through both — most filers haven\'t set this up.',
      step4_title: '4. Submit + track',
      step4_body: 'You file with CBP. We track the 60-day refund clock. When it hits your account, mark it received — we charge our fee on confirmed money, never on hope.',
    },
    pricing: {
      eyebrow: 'Pricing — only when you recover',
      tier1: '5% on first $50K recovered',
      tier2: '3% on $50K–$500K',
      tier3: '1.5% above $500K',
      floor: '$99 minimum on any successful claim',
      free: 'Free if no recovery — every step. No retainer.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free eligibility scan',
    sub: 'Drop your ACE Entry Summary CSV. We tell you what you\'re owed in under a minute. No signup, no payment, no commitment.',
    drop_label: 'Drop CSV here, or click to upload',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    parse_failed: 'CSV parse failed. Make sure it\'s an ACE Entry Summary export.',
    summary_title: 'Recovery summary',
    summary_total_recoverable: 'Total recoverable',
    summary_principal: 'IEEPA principal',
    summary_interest: 'Interest accrued',
    summary_cape_eligible: 'CAPE-eligible (Phase 1 fast lane)',
    summary_protest_required: 'Form 19 protest required',
    summary_past_window: 'Past 180-day window',
    summary_estimated_fee: 'Cruzar fee (only if recovered)',
    summary_net_to_you: 'Estimated net to you',
    cta_after: 'Sign up to compose the filing',
    cta_subnote: 'CAPE CSV + Form 19 packet + ACE/ACH onboarding included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
  },
};
