// lib/copy/refunds-es.ts
export const REFUNDS_ES = {
  landing: {
    eyebrow: 'Reembolsos IEEPA — para importadores EE.UU.',
    title: 'Pagaste aranceles IEEPA. La Corte Suprema los anuló. Te ayudamos a recuperar tu dinero.',
    sub: '$166 mil millones se deben a 330,000 importadores. 83% ni siquiera configuraron la cuenta bancaria para recibirlos. Empezamos ahí — gratis.',
    primary_cta: 'Escaneo gratis de elegibilidad',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa de plataforma: 8% del reembolso procesado · piso $99 · sin cargo en presentaciones rechazadas o vencidas',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'La UE tiene EORI. La frontera EE.UU.–México tiene Cruzar.',
    border_layer_body: 'En Europa, cada importador tiene un solo número EORI, cada operador de confianza gana estatus AEO, los registros aduanales están unificados en 27 países. En la frontera EE.UU.–México tienes ACE de un lado, VUCEM del otro, brokers fragmentados en medio, y cero registro compartido. Los Tickets Cruzar son ese registro unificado. Los reembolsos son uno de cinco módulos que corren sobre él — aduanas, regulatorio, papeleo, conductores, reembolsos. Construido en la frontera, para la frontera.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis de elegibilidad',
      step1_body: 'Sube tu CSV de ACE Entry Summary. Te decimos cuánto te deben en menos de un minuto. Sin registro.',
      step2_title: '2. Regístrate — obtén la presentación',
      step2_body: 'Componemos el CSV CAPE usando códigos de ingreso REV-615 (crédito CAPE) + REV-613 (seguimiento de rechazo ACH) — los códigos que lee el sistema de CBP desde que CAPE entró en vigor el 20 de abril de 2026. Para entradas cuya ventana de protesta de 80 días ya cerró, elaboramos un paquete de protesta Form 19. Ambos documentos están firmados con Ed25519.',
      step3_title: '3. Onboarding ACE / ACH',
      step3_body: 'No puedes recibir un reembolso sin cuenta del Portal ACE + inscripción ACH. Te guiamos por los dos — la mayoría de los filers no tienen esto configurado.',
      step4_title: '4. Envía + rastrea',
      step4_body: 'Tú presentas con CBP. Nosotros rastreamos el reloj de 60 días. Cuando llegue a tu cuenta, márcalo recibido — cobramos sobre dinero confirmado, nunca sobre esperanza.',
    },
    pricing: {
      eyebrow: 'Tarifa de plataforma — solo cuando llega el reembolso',
      rate: '8% del reembolso procesado a través de la plataforma Cruzar',
      floor: '$99 mínimo en cualquier reembolso procesado',
      no_fee: 'Sin cargo en presentaciones rechazadas, vencidas o retiradas — igual que los procesadores de pago no cobran transacciones declinadas',
      no_retainer: 'Sin anticipo. Sin suscripción. La tarifa solo se activa cuando CBP deposita el reembolso en tu ACH.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Escaneo gratis de elegibilidad',
    sub: 'Sube tu CSV de ACE Entry Summary. Te decimos cuánto te deben en menos de un minuto. Sin registro, sin pago, sin compromiso.',
    drop_label: 'Suelta el CSV aquí, o haz clic para subir',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa excedido — intenta en una hora.',
    parse_failed: 'Falló el parseo del CSV. Asegúrate de que sea un export de ACE Entry Summary.',
    summary_title: 'Resumen de recuperación',
    summary_total_recoverable: 'Total recuperable',
    summary_principal: 'Principal IEEPA',
    summary_interest: 'Interés acumulado',
    summary_cape_eligible: 'Elegible CAPE (Phase 1 rápido)',
    summary_protest_required: 'Requiere protesta Form 19',
    summary_past_window: 'Pasada ventana de 180 días',
    summary_estimated_fee: 'Tarifa de plataforma Cruzar (8% del reembolso procesado)',
    summary_net_to_you: 'Neto estimado para ti',
    cta_after: 'Regístrate para componer la presentación',
    cta_subnote: 'CSV CAPE + paquete Form 19 + onboarding ACE/ACH incluidos.',
  },
  setup: {
    eyebrow: 'Onboarding ACE / ACH',
    title: 'Configúrate para recibir tu reembolso',
    sub: '83% de los importadores no tiene esto configurado. CBP no te puede pagar sin cuenta del Portal ACE + inscripción ACH. 4 pasos. Rastreamos tu progreso.',
    step1_title: '1. Cuenta del Portal ACE',
    step1_body: 'Aplica en el Trade Portal de CBP. Toma 24-48 horas activarse.',
    step1_link_label: 'Inicio en el CBP Trade Portal →',
    step1_link_url: 'https://www.cbp.gov/trade/automated/getting-started',
    step2_title: '2. Autorización de Reembolso ACH',
    step2_body: 'En el Portal ACE, busca "ACH Refund Authorization." Ingresa el routing + cuenta del banco para el reembolso. Solo necesitamos los últimos 4 dígitos — para nuestros registros.',
    step3_title: '3. CBP Form 4811 (opcional)',
    step3_body: 'Form 4811 permite que un broker o agente reciba avisos en tu nombre. Opcional — sáltalo si tu broker no está involucrado.',
    step4_title: '4. Compila tu lista de entradas con IEEPA pagado',
    step4_body: 'En ACE Reports, corre un export de Entry Summary cubriendo el período IEEPA (1 feb 2025 en adelante). Guarda como CSV. Ese es el archivo que subes a Cruzar.',
    step4_link_label: 'Cómo correr un reporte ACE Entry Summary →',
    step4_link_url: 'https://www.cbp.gov/trade/ace',
    status_not_started: 'Sin empezar',
    status_pending: 'Pendiente',
    status_active: 'Activa',
    status_enrolled: 'Inscrito',
    save: 'Guardar progreso',
    saving: 'Guardando...',
    saved: 'Guardado.',
    bank_routing_label: 'Routing del banco — últimos 4 dígitos',
    bank_account_label: 'Cuenta del banco — últimos 4 dígitos',
  },
  claims: {
    eyebrow: 'Mis reclamos',
    title: 'Reclamos de reembolso',
    new_claim: 'Iniciar nuevo reclamo',
    empty_title: 'Aún sin reclamos',
    empty_body: 'Corre un escaneo gratis para ver cuánto te deben, después inicia un reclamo.',
    empty_cta: 'Correr escaneo gratis',
    col_id: 'Reclamo',
    col_ior: 'IOR',
    col_entries: 'Entradas',
    col_recoverable: 'Recuperable',
    col_status: 'Estado',
    col_updated: 'Actualizado',
    status_draft: 'Borrador',
    status_validated: 'Validado',
    status_submitted_to_ace: 'Enviado',
    status_refund_in_transit: 'En tránsito',
    status_refund_received: 'Recibido',
    status_rejected: 'Rechazado',
    new_form_title: 'Nuevo reclamo de reembolso',
    ior_name_label: 'Importador de Récord (nombre legal)',
    ior_id_label: 'Número IOR (EIN o asignado por CBP)',
    filer_code_label: 'Filer code (3 letras, opcional)',
    language_label: 'Idioma de la presentación',
    create: 'Crear borrador',
    creating: 'Creando...',
  },
  detail: {
    back: '← Volver a reclamos',
    section_summary: 'Resumen',
    section_entries: 'Entradas',
    section_actions: 'Acciones',
    label_ior: 'Importador de Récord',
    label_filer_code: 'Filer code',
    label_total_entries: 'Total de entradas',
    label_principal_owed: 'Principal adeudado',
    label_interest_owed: 'Interés acumulado',
    label_recoverable: 'Total recuperable',
    label_cape_eligible: 'Elegible CAPE',
    label_protest_required: 'Requiere protesta Form 19',
    label_past_window: 'Pasada ventana 180 días',
    label_status: 'Estado',
    label_cape_claim_number: 'Número de reclamo CAPE',
    label_received_amount: 'Monto recibido',
    label_cruzar_fee: 'Tarifa Cruzar',
    upload_label: 'Subir CSV de ACE Entry Summary',
    uploading: 'Subiendo + componiendo...',
    upload_help: 'Suelta tu CSV de ACE Entry Summary. Componemos CAPE + Form 19 y persistimos las entradas a este reclamo.',
    download_cape: 'Descargar CSV CAPE',
    download_form19: 'Descargar paquete Form 19',
    mark_submitted: 'Lo envié a ACE',
    mark_submitted_modal_title: 'Confirmar envío',
    mark_submitted_field: 'Número de reclamo CAPE (si CBP devolvió uno)',
    mark_received: 'Recibí el reembolso',
    mark_received_modal_title: 'Marcar reembolso recibido',
    mark_received_field: 'Monto real recibido (USD)',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    entry_col_number: 'Entrada #',
    entry_col_country: 'Origen',
    entry_col_eo: 'EO',
    entry_col_principal: 'IEEPA pagado',
    entry_col_interest: 'Interés',
    entry_col_cliff: 'Cliff',
    section_broker_of_record: 'Agente aduanal de récord',
    broker_of_record_help: 'Un agente aduanal licenciado debe revisar la presentación preparada y enviarla a CBP. Cruzar prepara; el agente presenta. Requerido antes del envío.',
    broker_name_label: 'Nombre del agente (firma o individual)',
    broker_license_label: 'Número de licencia CBP',
    broker_attest_label: 'Confirmo que este agente licenciado revisó el CSV CAPE preparado y (si aplica) el paquete Form 19, y será el agente aduanal de récord en esta presentación.',
    section_ior_attestation: 'Atestación del Importador de Récord',
    ior_attest_help: 'El Importador de Récord debe atestar que revisó la presentación y autoriza el envío. Declaraciones falsas en un reclamo de reembolso CBP pueden conllevar penalidades bajo 31 USC § 3729.',
    ior_attest_signer_label: 'Nombre del firmante (representante autorizado del Importador de Récord)',
    ior_attest_label: 'Estoy autorizado para actuar por el Importador de Récord. He revisado la presentación preparada y autorizo al agente de récord a enviarla a CBP en nombre del IOR.',
    save_attestation: 'Guardar atestación',
    saved: 'Guardado',
    submission_blocked_broker: 'Envío bloqueado — designa y atesta un agente aduanal licenciado de récord primero.',
    submission_blocked_ior: 'Envío bloqueado — el IOR debe atestar la presentación primero.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para preparar documentación de reembolsos CBP. Cruzar no realiza trámites ante CBP y no es un agente aduanal licenciado. Las presentaciones preparadas vía Cruzar deben ser revisadas y presentadas por el agente aduanal licenciado de récord. Los reembolsos los paga CBP directamente al ACH del importador; Cruzar nunca custodia el dinero del reembolso.',
  },
};
