// lib/copy/ticket-es.ts
export const TICKET_ES = {
  title: 'Boleto Cruzar',
  subtitle: 'Registro de validación de envío transfronterizo',
  issued_at: 'Emitido',
  ticket_id: 'ID del Boleto',
  modules_present: 'Módulos validados',
  shipment_section: 'Envío',
  origin: 'Origen',
  destination: 'Destino',
  importer: 'Importador',
  bol_ref: 'Ref BOL',
  customs_section: 'Validación aduanal',
  hs_classification: 'Clasificación HS',
  origin_status: 'Estado de origen',
  ligie_status: 'Estado LIGIE 2026',
  rvc_status: 'VCR',
  audit_shield: 'Escudo de auditoría',
  prior_disclosure: 'Elegible para divulgación previa (19 CFR § 162.74)',
  calibration: 'Calibración (últimos 30 días)',
  signature: 'Firma',
  verify_at: 'Verificar en',
  disclaimer: 'Este Boleto es documentación operativa privada. No es una credencial regulatoria. Verifique con su agente aduanal licenciado antes de presentar.',
  usmca_originating: 'Originario T-MEC',
  not_originating: 'No originario T-MEC',
  ligie_affected: 'Afectado por LIGIE',
  ligie_clear: 'LIGIE despejado',
  regulatory_section: 'Presentaciones regulatorias',
  agencies_required: 'Agencias',
  earliest_deadline: 'Plazo mas cercano',
};
