// lib/copy/ticket-en.ts
export const TICKET_EN = {
  title: 'Cruzar Ticket',
  subtitle: 'Cross-border shipment validation record',
  issued_at: 'Issued',
  ticket_id: 'Ticket ID',
  modules_present: 'Modules validated',
  shipment_section: 'Shipment',
  origin: 'Origin',
  destination: 'Destination',
  importer: 'Importer',
  bol_ref: 'BOL ref',
  customs_section: 'Customs validation',
  hs_classification: 'HS classification',
  origin_status: 'Origin status',
  ligie_status: 'LIGIE 2026 status',
  rvc_status: 'RVC',
  audit_shield: 'Audit shield',
  prior_disclosure: 'Prior-disclosure eligible (19 CFR § 162.74)',
  calibration: 'Calibration (last 30 days)',
  signature: 'Signature',
  verify_at: 'Verify at',
  disclaimer: 'This Ticket is private operational documentation. Not a regulatory credential. Verify with your licensed customs broker before filing.',
  usmca_originating: 'USMCA originating',
  not_originating: 'Not USMCA originating',
  ligie_affected: 'LIGIE-affected',
  ligie_clear: 'LIGIE clear',
  regulatory_section: 'Regulatory submissions',
  agencies_required: 'Agencies',
  earliest_deadline: 'Earliest deadline',
  paperwork_section: 'Paperwork extracted',
  documents: 'Documents',
  blocking: 'Blocking issues',
  drivers_section: 'Driver compliance',
  overall_status: 'Overall status',
  checks_run: 'Checks',
  refunds_section: 'IEEPA refund composition',
  refunds_total_recoverable: 'Total recoverable',
  refunds_cape_eligible: 'CAPE-eligible entries',
  refunds_protest_required: 'Form 19 protest required',
  refunds_registry_version: 'Registry version',
};
