// lib/copy/uflpa-en.ts
export const UFLPA_EN = {
  landing: {
    eyebrow: 'UFLPA — for U.S. importers with cross-border supply chains',
    title: 'CBP detains UFLPA-flagged imports at the port. Most importers don\'t know their tier-3 supplier is in Xinjiang until customs holds the container.',
    sub: 'Since June 21, 2022, any goods made wholly or in part in Xinjiang — or by entities on the UFLPA Entity List — face a rebuttable presumption of forced labor. CBP detains the shipment. The importer rebuts by clear-and-convincing evidence. Cotton, polysilicon, tomatoes, electronics, automotive parts, batteries, aluminum, PVC. Cruzar maps your supply chain, flags Xinjiang exposure before arrival, and pre-builds the rebuttal package.',
    primary_cta: 'Run a free UFLPA risk scan',
    secondary_cta: 'How it works',
    pricing_strip: 'Platform fee: 8% of declared shipment value protected · $99 floor · no fee if no rebuttal package needed',
    border_layer_eyebrow: 'The infrastructure layer',
    border_layer_title: 'UFLPA is one wall. Cruzar protects the corridor.',
    border_layer_body: 'UFLPA on US imports. CBAM on EU exports. EUDAMED on medtech. Pedimento on the Mexican side. Every wall around US-MX trade enforces a different filing. Cruzar Tickets are the unified record across them. UFLPA composes onto the same chassis — every shipment that crosses gets a forced-labor risk pass before the container ships.',
    how: {
      eyebrow: 'How it works',
      step1_title: '1. Free UFLPA risk scan',
      step1_body: 'Tell us your HTSUS + supply chain (tier 0 to tier N). We flag Xinjiang origin at any tier, match supplier names against the UFLPA Entity List, and surface CBP priority sectors.',
      step2_title: '2. Sign up — rebuttal package',
      step2_body: 'When risk fires, we compose the rebuttal package: full supply-chain map + supplier affidavit templates + audit-evidence checklist + transactional flow proof. CBP threshold: clear-and-convincing evidence.',
      step3_title: '3. Pre-arrival certainty',
      step3_body: 'You don\'t want to find out at the port. We surface flags 14+ days before expected arrival so your supply chain has time to substitute, source, or document.',
      step4_title: '4. Audit-ready archive',
      step4_body: 'Every UFLPA scan + rebuttal package signs into your Cruzar Ticket. If CBP holds a future shipment, the archive is your contemporaneous record per 19 CFR § 162.74.',
    },
    pricing: {
      eyebrow: 'Platform fee — paid only on shipments protected',
      rate: '8% of declared shipment value protected via rebuttal package',
      floor: '$99 minimum on any UFLPA scan with risk findings',
      no_fee: 'No fee if scan returns "low risk" — no rebuttal package needed',
      no_retainer: 'No retainer. No subscription. The platform fee fires when CBP clears your protected shipment.',
    },
    sectors: {
      eyebrow: 'CBP UFLPA priority sectors',
      cotton_title: 'Cotton + apparel (HTS 52, 61, 62)',
      cotton_body: 'Xinjiang produces ~85% of China\'s cotton. CBP fiber-tests apparel imports.',
      solar_title: 'Polysilicon + solar (HTS 2804, 8541)',
      solar_body: 'Xinjiang accounts for ~45% of global polysilicon. PV cell imports get heavy scrutiny.',
      tomatoes_title: 'Tomatoes + food (HTS 0702, 2002)',
      tomatoes_body: 'Xinjiang tomato paste exports trace through Italian/Chinese repackagers.',
      electronics_title: 'Electronics + semis (HTS 8471, 8517, 8542)',
      electronics_body: 'Server farms + telecom — Entity-List companies appear in tier 2-3.',
      auto_title: 'Automotive parts (HTS 8708)',
      auto_body: 'Xinjiang aluminum routes through tier 3 in many vehicle parts.',
      batteries_title: 'Lithium batteries (HTS 8507)',
      batteries_body: 'EV battery cathodes + cells trace through Chinese refiners.',
    },
  },
  scan: {
    eyebrow: 'Free public scan',
    title: 'Free UFLPA risk check',
    sub: 'Enter your HTSUS + supply chain (one row per tier). We flag Xinjiang exposure, match against the UFLPA Entity List, and tell you whether to ship or substitute. No signup, no payment.',
    section_importer: 'Importer',
    importer_name_label: 'Importer legal name',
    importer_ein_label: 'EIN',
    section_shipment: 'Shipment',
    htsus_label: 'HTSUS code (10 digits)',
    description_label: 'Product description',
    arrival_label: 'Expected arrival',
    port_label: 'Port of entry',
    declared_value_label: 'Declared value (USD)',
    section_supply_chain: 'Supply chain (tier 0 = direct supplier)',
    add_tier: 'Add tier',
    remove_tier: 'Remove',
    tier_label: 'Tier',
    supplier_label: 'Supplier name',
    country_label: 'Country (ISO-2)',
    province_label: 'Province / state',
    is_xinjiang_label: 'Produces in Xinjiang',
    is_entity_list_label: 'On UFLPA Entity List',
    has_audit_label: 'Audit evidence on file',
    has_affidavit_label: 'Supplier affidavit on file',
    submit: 'Run the UFLPA risk scan',
    scanning: 'Scanning...',
    rate_limited: 'Rate limited — try again in an hour.',
    summary_title: 'UFLPA risk evaluation',
    summary_risk_level: 'Risk level',
    summary_presumption: 'Rebuttable presumption',
    summary_xinjiang_tier: 'Xinjiang exposure tier',
    summary_xinjiang_none: 'No Xinjiang exposure detected',
    summary_entity_hits: 'Entity List matches',
    summary_sectors: 'Priority sectors detected',
    summary_evidence: 'Evidence quality',
    summary_actions: 'Required actions',
    summary_findings: 'Findings',
    summary_low_risk: 'Low risk — no rebuttable presumption triggered',
    cta_after: 'Sign up to compose the full rebuttal package',
    cta_subnote: 'Supply-chain map + affidavit templates + audit checklist included.',
  },
  shared: {
    nav_back: '← Back',
    powered_by: 'A Cruzar Ticket module · Built on the border, for the border',
    legal_disclaimer: 'Cruzar is software for preparing UFLPA risk documentation. Cruzar does not represent importers before CBP, does not provide legal advice, and is not a licensed customs broker. UFLPA rebuttals are submitted to CBP by the importer of record or the licensed customs broker of record using clear-and-convincing evidence per 19 USC § 1307 + Section 3 of Public Law 117-78.',
  },
};
