// lib/copy/uflpa-es.ts
export const UFLPA_ES = {
  landing: {
    eyebrow: 'UFLPA — para importadores US con cadenas transfronterizas',
    title: 'CBP detiene importaciones marcadas UFLPA en el puerto. La mayoría de importadores no saben que su proveedor de tier 3 está en Xinjiang hasta que aduanas detiene el contenedor.',
    sub: 'Desde el 21 de junio de 2022, cualquier mercancía hecha total o parcialmente en Xinjiang — o por entidades en la Lista de Entidades UFLPA — enfrenta una presunción refutable de trabajo forzado. CBP detiene el envío. El importador refuta con evidencia clara y convincente. Algodón, polisilicio, tomates, electrónica, autopartes, baterías, aluminio, PVC. Cruzar mapea tu cadena de suministro, marca exposición a Xinjiang antes del arribo, y pre-construye el paquete de refutación.',
    primary_cta: 'Corre un escaneo gratis',
    secondary_cta: 'Cómo funciona',
    pricing_strip: 'Tarifa plataforma: 8% del valor declarado del envío protegido · piso $99 · sin tarifa si no se necesita paquete de refutación',
    border_layer_eyebrow: 'La capa de infraestructura',
    border_layer_title: 'UFLPA es un muro. Cruzar protege el corredor.',
    border_layer_body: 'UFLPA en importaciones US. CBAM en exportaciones UE. EUDAMED en medtech. Pedimento del lado mexicano. Cada muro alrededor del comercio US-MX exige un trámite distinto. Los Cruzar Tickets son el registro unificado a través de ellos. UFLPA compone sobre el mismo chasis — cada envío que cruza recibe pase de riesgo de trabajo forzado antes de zarpar.',
    how: {
      eyebrow: 'Cómo funciona',
      step1_title: '1. Escaneo gratis de riesgo',
      step1_body: 'Dinos tu HTSUS + cadena de suministro (tier 0 a tier N). Marcamos origen Xinjiang en cualquier tier, comparamos nombres contra la Lista de Entidades UFLPA, y exponemos sectores prioritarios CBP.',
      step2_title: '2. Regístrate — paquete de refutación',
      step2_body: 'Cuando dispara riesgo, componemos el paquete: mapa completo de cadena + plantillas de declaración de proveedor + checklist de evidencia de auditoría + prueba de flujo transaccional. Umbral CBP: evidencia clara y convincente.',
      step3_title: '3. Certeza pre-arribo',
      step3_body: 'No quieres enterarte en el puerto. Mostramos las banderas 14+ días antes del arribo esperado para que tu cadena tenga tiempo de sustituir, abastecer o documentar.',
      step4_title: '4. Archivo listo para auditoría',
      step4_body: 'Cada escaneo UFLPA + paquete de refutación se firma en tu Cruzar Ticket. Si CBP detiene un envío futuro, el archivo es tu registro contemporáneo por 19 CFR § 162.74.',
    },
    pricing: {
      eyebrow: 'Tarifa plataforma — pagada solo sobre envíos protegidos',
      rate: '8% del valor declarado del envío protegido vía paquete de refutación',
      floor: '$99 mínimo en cualquier escaneo UFLPA con hallazgos de riesgo',
      no_fee: 'Sin tarifa si el escaneo regresa "riesgo bajo" — no se necesita paquete',
      no_retainer: 'Sin retainer. Sin suscripción. La tarifa se dispara cuando CBP libera tu envío protegido.',
    },
    sectors: {
      eyebrow: 'Sectores prioritarios UFLPA — CBP',
      cotton_title: 'Algodón + ropa (HTS 52, 61, 62)',
      cotton_body: 'Xinjiang produce ~85% del algodón de China. CBP hace análisis de fibra a las importaciones.',
      solar_title: 'Polisilicio + solar (HTS 2804, 8541)',
      solar_body: 'Xinjiang concentra ~45% del polisilicio global. Importaciones de celdas PV reciben fiscalización pesada.',
      tomatoes_title: 'Tomates + alimento (HTS 0702, 2002)',
      tomatoes_body: 'Pasta de tomate de Xinjiang se rastrea por reempacadores italianos/chinos.',
      electronics_title: 'Electrónica + semis (HTS 8471, 8517, 8542)',
      electronics_body: 'Servidores + telecom — empresas en Entity List aparecen en tier 2-3.',
      auto_title: 'Autopartes (HTS 8708)',
      auto_body: 'Aluminio de Xinjiang rutea por tier 3 en muchas autopartes.',
      batteries_title: 'Baterías litio (HTS 8507)',
      batteries_body: 'Cátodos de baterías EV + celdas se rastrean por refinadores chinos.',
    },
  },
  scan: {
    eyebrow: 'Escaneo público gratis',
    title: 'Verificación gratis de riesgo UFLPA',
    sub: 'Ingresa tu HTSUS + cadena de suministro (una fila por tier). Marcamos exposición Xinjiang, comparamos contra la Lista de Entidades UFLPA, y te decimos si zarpar o sustituir. Sin registro, sin pago.',
    section_importer: 'Importador',
    importer_name_label: 'Nombre legal del importador',
    importer_ein_label: 'EIN',
    section_shipment: 'Envío',
    htsus_label: 'Código HTSUS (10 dígitos)',
    description_label: 'Descripción del producto',
    arrival_label: 'Arribo esperado',
    port_label: 'Puerto de entrada',
    declared_value_label: 'Valor declarado (USD)',
    section_supply_chain: 'Cadena de suministro (tier 0 = proveedor directo)',
    add_tier: 'Agregar tier',
    remove_tier: 'Eliminar',
    tier_label: 'Tier',
    supplier_label: 'Nombre del proveedor',
    country_label: 'País (ISO-2)',
    province_label: 'Provincia / estado',
    is_xinjiang_label: 'Produce en Xinjiang',
    is_entity_list_label: 'En Lista de Entidades UFLPA',
    has_audit_label: 'Evidencia de auditoría en archivo',
    has_affidavit_label: 'Declaración de proveedor en archivo',
    submit: 'Corre el escaneo de riesgo UFLPA',
    scanning: 'Escaneando...',
    rate_limited: 'Límite de tasa — intenta en una hora.',
    summary_title: 'Evaluación de riesgo UFLPA',
    summary_risk_level: 'Nivel de riesgo',
    summary_presumption: 'Presunción refutable',
    summary_xinjiang_tier: 'Tier de exposición Xinjiang',
    summary_xinjiang_none: 'Sin exposición Xinjiang detectada',
    summary_entity_hits: 'Coincidencias Lista de Entidades',
    summary_sectors: 'Sectores prioritarios detectados',
    summary_evidence: 'Calidad de evidencia',
    summary_actions: 'Acciones requeridas',
    summary_findings: 'Hallazgos',
    summary_low_risk: 'Riesgo bajo — sin presunción refutable activada',
    cta_after: 'Regístrate para componer el paquete completo de refutación',
    cta_subnote: 'Mapa de cadena + plantillas de declaración + checklist de auditoría incluidos.',
  },
  shared: {
    nav_back: '← Volver',
    powered_by: 'Un módulo Cruzar Ticket · Construido en la frontera, para la frontera',
    legal_disclaimer: 'Cruzar es software para preparar documentación de riesgo UFLPA. Cruzar no representa importadores ante CBP, no provee asesoría legal, y no es un agente aduanal licenciado. Las refutaciones UFLPA las presenta el importador de registro o el agente aduanal licenciado responsable usando evidencia clara y convincente según 19 USC § 1307 + Sección 3 de la Ley Pública 117-78.',
  },
};
