'use client'

export type Lang = 'en' | 'es'

export const translations = {
  en: {
    appName: 'Cruza',
    subtitle: 'Live border wait times',
    allRegions: '📍 All Regions',
    enteringUS: '🇺🇸 Entering the US',
    enteringMexico: '🇲🇽 Entering Mexico',
    updatedJustNow: 'Updated just now',
    updatedAgo: (m: number) => `Updated ${m}m ago`,
    list: 'List',
    map: 'Map',
    tapDot: 'Tap a dot to see details',
    noData: 'No port data available.',
    car: 'Car',
    sentri: 'SENTRI',
    walk: 'Walk',
    truck: 'Truck',
    carsAhead: (n: number) => `~${n} cars`,
    closed: 'Closed',
    signUpFree: 'Sign Up Free',
    localBusiness: 'Advertise',
    me: 'Me',
    underMin: 'Under 20 min',
    midMin: '20–45 min',
    overMin: '45+ min',
    mexicoSideTitle: 'Mexico-side wait times',
    mexicoSideDesc: 'No official data exists for crossing into Mexico — Mexico doesn\'t publish wait times publicly. Wait times entering Mexico are typically under 5 minutes.',
    communityTip: '💡 Community tip',
    communityTipDesc: 'Returning to Mexico is usually quick — Mexican customs rarely causes delays. Busy periods are Friday afternoons and weekends when US-side shoppers return.',
    createAccount: 'Create a free account',
    toSeeLocalDeals: 'to see local deals instead of ads',
    // Report form
    reportTitle: 'What\'s happening at this crossing?',
    reportSubmit: 'Submit Report',
    reportSubmitting: 'Submitting...',
    reportDone: 'Report submitted — thanks!',
    reportPlaceholder: 'Optional details (lane, cause, etc.)',
    reportLong: 'Long Delay',
    reportInspection: 'Inspection',
    reportAccident: 'Accident',
    reportClear: 'Moving Fast',
    reportOther: 'Other',
    // Just Crossed
    justCrossedTitle: (port: string) => `Just crossed at ${port}?`,
    justCrossedSub: 'Help others + earn points',
    justCrossedFast: 'Fast',
    justCrossedNormal: 'Normal',
    justCrossedSlow: 'Slow',
    justCrossedMinutes: 'Actual wait in minutes (optional)',
    justCrossedSubmit: 'Submit Report',
    justCrossedThanks: 'Thanks! ¡Gracias!',
    justCrossedHelping: 'You\'re helping fellow crossers.',
    // Nav/UI
    allCrossings: 'All crossings',
    recentReports: 'Recent community reports',
    noReports: 'No reports in the last 24 hours.',
    beFirst: 'Be the first to report!',
    anonymous: 'Anonymous',
    justNow: 'just now',
    ago: (m: number) => `${m}m ago`,
    hoursAgo: (h: number) => `${h}h ago`,
    plannerBannerTitle: '🔮 Smart Crossing Planner',
    plannerBannerSub: 'See the best time to cross — any port, any day',
    plannerTry: 'Try it →',
    // Lane labels
    laneCar: 'Car',
    laneSentri: 'SENTRI',
    laneWalk: 'Walk',
    laneTruck: 'Truck',
    // Wait states
    noWaitLowTraffic: 'No wait · Low traffic',
    lessThanMin: '< 1 min',
    // PortList legend
    legendNoWait: 'No / low wait',
    // Services
    servicesLink: 'Services in MX →',
  },
  es: {
    appName: 'Cruza',
    subtitle: 'Tiempos de espera en la frontera en vivo',
    allRegions: '📍 Todas las regiones',
    enteringUS: '🇺🇸 Entrando a EE.UU.',
    enteringMexico: '🇲🇽 Entrando a México',
    updatedJustNow: 'Actualizado ahora mismo',
    updatedAgo: (m: number) => `Actualizado hace ${m} min`,
    list: 'Lista',
    map: 'Mapa',
    tapDot: 'Toca un punto para ver detalles',
    noData: 'No hay datos disponibles.',
    car: 'Auto',
    sentri: 'SENTRI',
    walk: 'Peatón',
    truck: 'Camión',
    carsAhead: (n: number) => `~${n} autos`,
    closed: 'Cerrado',
    signUpFree: 'Regístrate Gratis',
    localBusiness: 'Publicidad',
    me: 'Yo',
    underMin: 'Menos de 20 min',
    midMin: '20–45 min',
    overMin: 'Más de 45 min',
    mexicoSideTitle: 'Tiempos del lado mexicano',
    mexicoSideDesc: 'No existen datos oficiales para cruzar a México. Entrar a México generalmente toma menos de 5 minutos.',
    communityTip: '💡 Consejo de la comunidad',
    communityTipDesc: 'Regresar a México suele ser rápido. Los períodos más ocupados son los viernes por la tarde y los fines de semana.',
    createAccount: 'Crea una cuenta gratis',
    toSeeLocalDeals: 'para ver ofertas locales en vez de anuncios',
    // Report form
    reportTitle: '¿Qué está pasando en este cruce?',
    reportSubmit: 'Enviar Reporte',
    reportSubmitting: 'Enviando...',
    reportDone: '¡Reporte enviado — gracias!',
    reportPlaceholder: 'Detalles opcionales (carril, causa, etc.)',
    reportLong: 'Demora larga',
    reportInspection: 'Inspección',
    reportAccident: 'Accidente',
    reportClear: 'Fluye rápido',
    reportOther: 'Otro',
    // Just Crossed
    justCrossedTitle: (port: string) => `¿Acabas de cruzar en ${port}?`,
    justCrossedSub: 'Ayuda a otros + gana puntos',
    justCrossedFast: 'Rápido',
    justCrossedNormal: 'Normal',
    justCrossedSlow: 'Lento',
    justCrossedMinutes: 'Tiempo real de espera en minutos (opcional)',
    justCrossedSubmit: 'Enviar Reporte',
    justCrossedThanks: '¡Gracias! Thanks!',
    justCrossedHelping: 'Estás ayudando a otros cruzantes.',
    // Nav/UI
    allCrossings: 'Todos los cruces',
    recentReports: 'Reportes recientes de la comunidad',
    noReports: 'Sin reportes en las últimas 24 horas.',
    beFirst: '¡Sé el primero en reportar!',
    anonymous: 'Anónimo',
    justNow: 'justo ahora',
    ago: (m: number) => `hace ${m} min`,
    hoursAgo: (h: number) => `hace ${h}h`,
    plannerBannerTitle: '🔮 Planificador Inteligente',
    plannerBannerSub: 'Encuentra el mejor horario para cruzar',
    plannerTry: 'Probar →',
    // Lane labels
    laneCar: 'Auto',
    laneSentri: 'SENTRI',
    laneWalk: 'Peatón',
    laneTruck: 'Camión',
    // Wait states
    noWaitLowTraffic: 'Sin espera · Poco tráfico',
    lessThanMin: '< 1 min',
    // PortList legend
    legendNoWait: 'Sin espera',
    // Services
    servicesLink: 'Servicios en MX →',
  },
}

export type T = typeof translations.en
