import Link from "next/link";

// /dispatch/paperwork — paperwork generator hub.
//
// v0 ships USMCA Certificate of Origin only — 9 data elements per Article 5.2,
// no prescribed form, lowest-risk first form to ship. Other forms queued behind
// it (CBP 7501, DODA, Pedimento, Carta Porte / CCP) — each is a much bigger
// build with stricter format requirements. Ship one well, learn, expand.

export const metadata = {
  title: "Cruzar Dispatch — paperwork generator",
};

interface FormCard {
  href: string | null;
  title: string;
  description: string;
  status: "live" | "queued";
  pain: string;
}

const FORMS: FormCard[] = [
  {
    href: "/dispatch/paperwork/usmca",
    title: "USMCA Certificate of Origin",
    description:
      "9 prescribed data elements per USMCA Article 5.2. No prescribed form — generate, sign, attach to your invoice for duty-free preferential treatment.",
    status: "live",
    pain: "Missing or wrong = full duty assessed at entry. Up to 4× duty for negligence per 19 USC § 1592.",
  },
  {
    href: null,
    title: "CBP Form 7501 (Entry Summary)",
    description:
      "Filed within 10 business days of entry. Classification, value, duty rate, country of origin, preferential program claims.",
    status: "queued",
    pain: "Errors on this form create direct penalty exposure under 19 USC § 1592. Auto-fill from invoice + USMCA cert next.",
  },
  {
    href: null,
    title: "DODA (Documento de Operación para Despacho Aduanero)",
    description:
      "MX-side document scanned at the booth via PITA RFID. Generated by aduanal broker today.",
    status: "queued",
    pain: 'Missing the "T" in T1000 trailer number = wrong paperwork = trailer seized at the border (verbatim from broker research).',
  },
  {
    href: null,
    title: "Pedimento",
    description:
      "MX customs declaration. SAT VUCEM portal. Includes tariff classification (TIGIE), value, duty calculation.",
    status: "queued",
    pain: "Auto-fill from supplier invoice + USMCA cert + carta porte. Largest single document drag in cross-border.",
  },
  {
    href: null,
    title: "Carta Porte / CCP (CFDI 4.0)",
    description:
      "Mandatory in MX since 2022. Bill of lading with goods + transport details.",
    status: "queued",
    pain: "Without valid carta porte SAT can seize the trailer in transit.",
  },
];

export default function PaperworkHub() {
  return (
    <main className="mx-auto max-w-[1180px] px-5 sm:px-8 py-6">
      <div className="mb-6">
        <h1 className="text-[1.4rem] font-semibold text-white">
          Paperwork <span className="text-white/40 text-base font-normal">· trámites</span>
        </h1>
        <p className="mt-1 text-[13px] text-white/55 max-w-2xl">
          Generate the cross-border paperwork your aduanal broker normally hand-types. We pre-fill,
          you verify, you sign. Saves 30+ min per load and eliminates the trailer-seizure errors.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        {FORMS.map((f) => {
          const isLive = f.status === "live";
          const inner = (
            <div
              className={`rounded-2xl border p-5 h-full transition ${
                isLive
                  ? "border-amber-300/30 bg-amber-300/[0.02] hover:border-amber-300/60 hover:bg-amber-300/[0.05]"
                  : "border-white/[0.07] bg-white/[0.015]"
              }`}
            >
              <div className="flex items-baseline justify-between gap-3 mb-2">
                <h2 className={`text-[15px] font-semibold ${isLive ? "text-white" : "text-white/55"}`}>
                  {f.title}
                </h2>
                <span
                  className={`rounded-full px-2 py-0.5 text-[10px] uppercase tracking-[0.12em] font-medium ${
                    isLive
                      ? "bg-emerald-500/15 text-emerald-300 border border-emerald-400/30"
                      : "bg-white/[0.05] text-white/35 border border-white/[0.08]"
                  }`}
                >
                  {isLive ? "live" : "queued"}
                </span>
              </div>
              <p className={`text-[12.5px] leading-[1.55] ${isLive ? "text-white/65" : "text-white/40"}`}>
                {f.description}
              </p>
              <p
                className={`mt-3 pt-3 border-t border-white/[0.05] text-[11.5px] leading-[1.5] italic ${
                  isLive ? "text-rose-200/70" : "text-white/30"
                }`}
              >
                Pain: {f.pain}
              </p>
              {isLive && (
                <div className="mt-4 text-[12px] text-amber-300 group">
                  Open generator <span className="inline-block transition group-hover:translate-x-0.5">→</span>
                </div>
              )}
            </div>
          );
          return f.href ? (
            <Link key={f.title} href={f.href} className="block">
              {inner}
            </Link>
          ) : (
            <div key={f.title}>{inner}</div>
          );
        })}
      </div>

      <p className="mt-8 text-[11px] text-white/35 leading-[1.55]">
        We generate, you verify. Cruzar is not a customs broker; the generator pre-fills based on
        your inputs and USMCA Article 5.2 / 19 CFR § 141.86 conventions. Your aduanal broker / CHB
        owns the legal filing. Drafts saved to this browser only — nothing leaves your machine
        unless you copy it out.
      </p>
    </main>
  );
}
