// Public surface for the tracking module. New call sites should import
// the typed helpers from here so PostHog event names + properties stay
// validated by TypeScript.
//
// Legacy lib/trackEvent.ts (used by the existing 81 call sites) imports
// captureLegacy() from this module and routes the snake_case events into
// PostHog with the alias map applied — no call-site changes required.

export { EVENTS, LEGACY_TO_POSTHOG } from './events';
export type { EventName } from './events';
export type {
  UserTraits,
  BusinessAccountTraits,
  Tier,
  InstallState,
  Language,
  SignupMethod,
  UserSignedUpProps,
  UserSignedInProps,
  UserAccountDeletedProps,
  InstallVariant,
  InstallCompletedProps,
  HomeVisitedProps,
  PortViewedProps,
  CrossingSavedProps,
  CrossingUnsavedProps,
  LaneType,
  AlertCreatedProps,
  AlertRemovedProps,
  AlertChannel,
  AlertDeliveredProps,
  AlertOpenedProps,
  SmartRouteRequestedProps,
  BestTimesViewedProps,
  ReportType,
  ReportSource,
  ReportSubmittedProps,
  ReportUpvotedProps,
  WaitConfirmVotedProps,
  PhotoSubmittedProps,
  AutoCrossingProps,
  PushOutcome,
  PushPermissionPromptedProps,
  PushPermissionResolvedProps,
  DriverAddedProps,
  DriverRemovedProps,
  ShipmentStatus,
  DriverCheckedInProps,
  ShipmentCreatedProps,
  ShipmentStatusChangedProps,
  FleetExportRequestedProps,
  PricingViewedProps,
  CheckoutTier,
  CheckoutProvider,
  CheckoutStartedProps,
  SubscriptionActivatedProps,
  SubscriptionRenewedProps,
  SubscriptionCanceledProps,
  PwaGrantClaimedProps,
  ShareChannel,
  ShareExecutedProps,
  ReferralLinkVisitedProps,
  FbPageFollowClickedProps,
  LanguageChangedProps,
  InstallNudgeShownProps,
  InstallNudgeOutcome,
  InstallNudgeResolvedProps,
  OutboundAffiliateClickedProps,
  BusinessClickType,
  OutboundBusinessClickedProps,
  InsightsViewedProps,
} from './types';

export { identifyUser, resetIdentity, groupBusinessAccount } from './identify';
export {
  capture,
  captureLegacy,
  trackUserSignedUp,
  trackUserSignedIn,
  trackUserSignedOut,
  trackUserAccountDeleted,
  trackInstallCompleted,
  trackHomeVisited,
  trackPortViewed,
  trackCrossingSaved,
  trackCrossingUnsaved,
  trackAlertCreated,
  trackAlertRemoved,
  trackAlertOpened,
  trackSmartRouteRequested,
  trackBestTimesViewed,
  trackReportSubmitted,
  trackReportUpvoted,
  trackWaitConfirmVoted,
  trackPhotoSubmitted,
  trackAutoCrossingDetected,
  trackAutoCrossingConfirmed,
  trackAutoCrossingRejected,
  trackPushPermissionPrompted,
  trackPushPermissionResolved,
  trackDriverAdded,
  trackDriverRemoved,
  trackShipmentCreated,
  trackFleetDashboardViewed,
  trackFleetExportRequested,
  trackPricingViewed,
  trackCheckoutStarted,
  trackPwaGrantClaimed,
  trackShareExecuted,
  trackReferralLinkVisited,
  trackFbPageFollowClicked,
  trackLanguageChanged,
  trackInstallNudgeShown,
  trackInstallNudgeResolved,
  trackOutboundAffiliateClicked,
  trackOutboundBusinessClicked,
  trackInsightsViewed,
  trackPricingTableViewed,
} from './track';

// Server helpers live in lib/tracking/posthog-server.ts. They are NOT
// re-exported here — importing them through the barrel would pull
// posthog-node (which depends on node:fs) into client bundles and break
// Turbopack. Server callers should import directly:
//
//   import { trackServer, flushServerPostHog } from '@/lib/tracking/posthog-server'
