import React from 'react';
import {
  AbsoluteFill,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
  Easing,
} from 'remotion';
import { z } from 'zod';

// Daily organic "current wait times" composition — upgraded 2026-04-15.
// Renders every 4 hours at pre-peak windows via GitHub Actions.
// Built for silent autoplay on FB/IG/TikTok feeds: all messaging is
// visual + typographic, no voiceover, captions baked in.
//
// Design changes from v1:
//   - Logo bumper (0-1.2s) with brand color pulse
//   - Pre-title context row ("es lunes · 5:42 AM CT")
//   - Headline animation with stagger + ease curve (not just spring)
//   - Card rows use actual typographic hierarchy (uppercase eyebrow + display num + unit)
//   - Subtle background grid + vignette for depth
//   - Fastest bridge badge with gold accent
//   - End frame with CTA + QR code area + progress bar for "first 1000 promo"
//
// Caption (baked-in text) is generated by render.mjs and also emitted
// as a separate .txt file for Make.com to pick up.

export const WaitTimeVideoSchema = z.object({
  crossings: z.array(
    z.object({
      portId: z.string(),
      name: z.string(),
      wait: z.number(),
      level: z.enum(['low', 'medium', 'high', 'unknown']),
      lanesOpen: z.number().nullable().optional(),
    })
  ),
  // Real numbers from /api/stats/community so the video cites current state
  totalUsers: z.number().optional(),
  promoRemaining: z.number().optional(),
  reportsLast24h: z.number().optional(),
});

type Props = z.infer<typeof WaitTimeVideoSchema>;

const COLORS = {
  low:     '#22c55e',
  medium:  '#f59e0b',
  high:    '#ef4444',
  unknown: '#6b7280',
};

const LABELS = {
  low:     'RÁPIDO',
  medium:  'MODERADO',
  high:    'LENTO',
  unknown: 'SIN DATOS',
};

const FPS = 30;

// Scene timing (in frames at 30fps)
const LOGO_BUMPER_END = 36;       // 1.2s
const HEADLINE_START  = LOGO_BUMPER_END;
const HEADLINE_HOLD   = HEADLINE_START + 36;  // 2.4s total for headline
const CARDS_START     = HEADLINE_HOLD;
const CARD_STAGGER    = 7;         // 0.23s between each card
const CTA_START_OFFSET = 18;       // frames before end

function useBgGrid(frame: number) {
  // Slow parallax drift on the grid lines — gives depth without feeling busy
  const drift = interpolate(frame, [0, 300], [0, 30]);
  return drift;
}

function LogoBumper({ frame }: { frame: number }) {
  const opacity = interpolate(frame, [0, 6, LOGO_BUMPER_END - 6, LOGO_BUMPER_END], [0, 1, 1, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.inOut(Easing.cubic),
  });
  const scale = interpolate(frame, [0, LOGO_BUMPER_END], [0.92, 1.04], {
    easing: Easing.out(Easing.cubic),
  });
  const pulseOpacity = interpolate(
    frame,
    [0, LOGO_BUMPER_END / 2, LOGO_BUMPER_END],
    [0, 0.5, 0],
    { extrapolateRight: 'clamp' }
  );
  return (
    <AbsoluteFill style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', opacity }}>
      <div style={{ position: 'relative', transform: `scale(${scale})` }}>
        <div
          style={{
            position: 'absolute',
            inset: -40,
            background: 'radial-gradient(circle, rgba(59,130,246,0.55) 0%, transparent 70%)',
            opacity: pulseOpacity,
            filter: 'blur(20px)',
          }}
        />
        <div
          style={{
            width: 220,
            height: 220,
            borderRadius: 48,
            background: 'linear-gradient(135deg, #1e40af 0%, #3730a3 100%)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: '0 40px 80px rgba(30,64,175,0.4)',
            position: 'relative',
          }}
        >
          <svg viewBox="0 0 80 80" width={120} height={120}>
            <path
              d="M 10 50 Q 40 15 70 50"
              fill="none"
              stroke="white"
              strokeWidth={7}
              strokeLinecap="round"
            />
            <line x1={10} y1={50} x2={10} y2={62} stroke="white" strokeWidth={7} strokeLinecap="round" />
            <line x1={70} y1={50} x2={70} y2={62} stroke="white" strokeWidth={7} strokeLinecap="round" />
          </svg>
        </div>
        <div
          style={{
            marginTop: 32,
            textAlign: 'center',
            fontSize: 54,
            fontWeight: 900,
            color: 'white',
            letterSpacing: -1,
            textTransform: 'lowercase',
          }}
        >
          cruzar
        </div>
      </div>
    </AbsoluteFill>
  );
}

function CrossingRow({
  crossing,
  index,
  totalCards,
  isFastest,
}: {
  crossing: Props['crossings'][0];
  index: number;
  totalCards: number;
  isFastest: boolean;
}) {
  const frame = useCurrentFrame();
  const startFrame = CARDS_START + index * CARD_STAGGER;
  const progress = Math.max(0, Math.min(1, (frame - startFrame) / 22));

  const translateX = interpolate(progress, [0, 1], [-60, 0], {
    easing: Easing.out(Easing.cubic),
  });
  const opacity = interpolate(progress, [0, 0.6], [0, 1], { extrapolateRight: 'clamp' });

  const countStart = startFrame + 3;
  const countEnd = startFrame + 18;
  const displayedWait = Math.round(
    interpolate(frame, [countStart, countEnd], [0, crossing.wait], {
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
      easing: Easing.out(Easing.cubic),
    })
  );

  const color = COLORS[crossing.level];
  const isZero = crossing.wait === 0 && crossing.level === 'low';
  const isUnknown = crossing.level === 'unknown';

  return (
    <div
      style={{
        opacity,
        transform: `translateX(${translateX}px)`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        background: isFastest
          ? 'linear-gradient(90deg, rgba(34,197,94,0.12), rgba(255,255,255,0.03))'
          : 'rgba(255,255,255,0.045)',
        borderRadius: 22,
        padding: '24px 34px',
        marginBottom: 14,
        borderLeft: `8px solid ${color}`,
        border: isFastest ? `2px solid ${color}` : undefined,
        backdropFilter: 'blur(4px)',
      }}
    >
      <div style={{ flex: 1, minWidth: 0 }}>
        {isFastest && (
          <div
            style={{
              display: 'inline-block',
              fontSize: 16,
              fontWeight: 900,
              color: '#22c55e',
              background: 'rgba(34,197,94,0.15)',
              padding: '3px 10px',
              borderRadius: 999,
              letterSpacing: 2,
              marginBottom: 6,
              textTransform: 'uppercase',
            }}
          >
            ⚡ MÁS RÁPIDO
          </div>
        )}
        <div
          style={{
            fontSize: 36,
            fontWeight: 800,
            color: 'white',
            lineHeight: 1.05,
            letterSpacing: -0.5,
          }}
        >
          {crossing.name}
        </div>
        <div
          style={{
            fontSize: 18,
            fontWeight: 700,
            color,
            marginTop: 6,
            letterSpacing: 1.5,
          }}
        >
          {LABELS[crossing.level]}
          {crossing.lanesOpen != null && crossing.lanesOpen > 0 && (
            <span style={{ color: 'rgba(255,255,255,0.4)', fontWeight: 600, marginLeft: 10 }}>
              · {crossing.lanesOpen} {crossing.lanesOpen === 1 ? 'carril' : 'carriles'}
            </span>
          )}
        </div>
      </div>
      <div style={{ textAlign: 'right', marginLeft: 24 }}>
        {isUnknown ? (
          <>
            <div style={{ fontSize: 64, fontWeight: 900, color, lineHeight: 0.9 }}>—</div>
            <div style={{ fontSize: 18, color: 'rgba(255,255,255,0.4)', marginTop: 2, letterSpacing: 1 }}>
              MIN
            </div>
          </>
        ) : isZero ? (
          <>
            <div
              style={{
                fontSize: 52,
                fontWeight: 900,
                color,
                lineHeight: 0.9,
                letterSpacing: 2,
              }}
            >
              LIBRE
            </div>
            <div style={{ fontSize: 16, color: 'rgba(255,255,255,0.55)', marginTop: 4, letterSpacing: 1 }}>
              PASA YA
            </div>
          </>
        ) : (
          <>
            <div
              style={{
                fontSize: 80,
                fontWeight: 900,
                color,
                lineHeight: 0.9,
                fontFeatureSettings: '"tnum"',
              }}
            >
              {displayedWait}
            </div>
            <div style={{ fontSize: 18, color: 'rgba(255,255,255,0.4)', marginTop: 2, letterSpacing: 1 }}>
              MIN
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export const WaitTimeVideo: React.FC<Props> = ({
  crossings,
  totalUsers = 153,
  promoRemaining,
  reportsLast24h = 16,
}) => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  // Find fastest for highlight — lowest wait that's NOT unknown and NOT zero
  const sortedByWait = [...crossings].filter((c) => c.level !== 'unknown');
  const fastestId = sortedByWait.length > 0
    ? sortedByWait.reduce((best, c) => (c.wait < best.wait ? c : best)).portId
    : null;

  const gridDrift = useBgGrid(frame);

  // Headline entrance — title fades in + lifts up from below
  const headlineProgress = Math.max(0, Math.min(1, (frame - HEADLINE_START) / 24));
  const headlineOpacity = interpolate(headlineProgress, [0, 0.7], [0, 1], { extrapolateRight: 'clamp' });
  const headlineY = interpolate(headlineProgress, [0, 1], [28, 0], { easing: Easing.out(Easing.cubic) });

  // Blinking live dot
  const blinkCycle = frame % 27;
  const blinkOpacity = interpolate(blinkCycle, [0, 13, 27], [1, 0.2, 1], { extrapolateRight: 'clamp' });

  // End CTA fade-in — last ~1.8s of the video
  const ctaStart = durationInFrames - 54;
  const ctaProgress = Math.max(0, Math.min(1, (frame - ctaStart) / 24));
  const ctaOpacity = interpolate(ctaProgress, [0, 1], [0, 1], { extrapolateRight: 'clamp' });
  const ctaY = interpolate(ctaProgress, [0, 1], [30, 0], { easing: Easing.out(Easing.cubic) });

  const now = new Date();
  const timeStr = now.toLocaleTimeString('es-MX', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
    timeZone: 'America/Chicago',
  });
  const dowShort = new Intl.DateTimeFormat('es-MX', { weekday: 'long', timeZone: 'America/Chicago' })
    .format(now)
    .toUpperCase();

  const promoText = promoRemaining != null && promoRemaining > 0
    ? `${1000 - promoRemaining} / 1000 · quedan ${promoRemaining} cupos de Pro gratis`
    : `+${totalUsers} personas en la comunidad`;

  return (
    <AbsoluteFill
      style={{
        background: 'linear-gradient(160deg, #0a1430 0%, #111a3a 50%, #1a1f4a 100%)',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, sans-serif',
      }}
    >
      {/* Subtle grid background for depth */}
      <AbsoluteFill
        style={{
          backgroundImage:
            'linear-gradient(rgba(255,255,255,0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.025) 1px, transparent 1px)',
          backgroundSize: '80px 80px',
          backgroundPosition: `0 ${gridDrift}px`,
          opacity: 0.6,
        }}
      />
      {/* Top-right glow */}
      <AbsoluteFill
        style={{
          background: 'radial-gradient(circle at 85% 10%, rgba(59,130,246,0.18) 0%, transparent 50%)',
        }}
      />
      {/* Bottom vignette */}
      <AbsoluteFill
        style={{
          background:
            'linear-gradient(to bottom, transparent 60%, rgba(0,0,0,0.45) 100%)',
        }}
      />

      {/* Logo bumper — covers everything below for the first 1.2s */}
      {frame < LOGO_BUMPER_END && <LogoBumper frame={frame} />}

      {frame >= HEADLINE_START && (
        <div
          style={{
            position: 'absolute',
            inset: 0,
            padding: '92px 48px 56px 48px',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          {/* Context row */}
          <div
            style={{
              opacity: headlineOpacity,
              transform: `translateY(${headlineY}px)`,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 16,
              marginBottom: 18,
            }}
          >
            <div
              style={{
                width: 14,
                height: 14,
                borderRadius: '50%',
                background: '#ef4444',
                opacity: blinkOpacity,
                boxShadow: `0 0 20px rgba(239,68,68,${blinkOpacity * 0.8})`,
              }}
            />
            <span style={{ fontSize: 22, fontWeight: 700, color: '#ef4444', letterSpacing: 3 }}>
              EN VIVO
            </span>
            <span style={{ fontSize: 20, color: 'rgba(255,255,255,0.45)', letterSpacing: 2 }}>
              · {dowShort} · {timeStr}
            </span>
          </div>

          {/* Headline */}
          <div
            style={{
              opacity: headlineOpacity,
              transform: `translateY(${headlineY}px)`,
              textAlign: 'center',
              marginBottom: 44,
            }}
          >
            <div
              style={{
                fontSize: 82,
                fontWeight: 900,
                color: 'white',
                lineHeight: 0.95,
                letterSpacing: -2,
              }}
            >
              TIEMPOS EN
              <br />
              LOS PUENTES
            </div>
          </div>

          {/* Cards */}
          <div style={{ flex: 1 }}>
            {crossings.map((crossing, i) => (
              <CrossingRow
                key={crossing.portId}
                crossing={crossing}
                index={i}
                totalCards={crossings.length}
                isFastest={crossing.portId === fastestId}
              />
            ))}
          </div>

          {/* End CTA */}
          <div
            style={{
              opacity: ctaOpacity,
              transform: `translateY(${ctaY}px)`,
              textAlign: 'center',
              paddingTop: 32,
              borderTop: '1px solid rgba(255,255,255,0.12)',
              marginTop: 14,
            }}
          >
            <div
              style={{
                fontSize: 22,
                fontWeight: 700,
                color: 'rgba(255,255,255,0.5)',
                letterSpacing: 3,
                textTransform: 'uppercase',
                marginBottom: 6,
              }}
            >
              VE TODOS EN VIVO
            </div>
            <div style={{ fontSize: 56, fontWeight: 900, color: 'white', letterSpacing: -1, marginBottom: 8 }}>
              cruzar.app
            </div>
            <div style={{ fontSize: 18, color: '#fbbf24', fontWeight: 700, letterSpacing: 1 }}>
              {promoText}
            </div>
          </div>
        </div>
      )}
    </AbsoluteFill>
  );
};
